
-- https://dbdocs.io/profesionalemailame/DentalMate?view=relationships
-- https://mermaid.ai/d/74b23dea-9ada-4e1b-88b9-3ea976a48c19

BEGIN;

-- =========================================================
-- 0) Roles base (ejecutar como superuser o rol con permisos)
-- =========================================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_owner') THEN
    CREATE ROLE app_owner NOINHERIT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_user') THEN
    CREATE ROLE app_user NOINHERIT;
  END IF;

  -- Rol técnico para funciones SECURITY DEFINER que necesitan bypass RLS solo para membership.
  -- Requiere permisos para crear roles con BYPASSRLS (normalmente superuser).
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_rls') THEN
    CREATE ROLE app_rls NOINHERIT BYPASSRLS;
  END IF;
END$$;

-- Endurecer schema public (opcional pero recomendado en entornos reales)
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO app_user;
GRANT USAGE, CREATE ON SCHEMA public TO app_owner;

-- Extensión para EXCLUDE con igualdad sobre int (btree) + rangos (gist)
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- =========================================================
-- 1) ENUMs
-- =========================================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Citas_estado_enum') THEN
    CREATE TYPE "Citas_estado_enum" AS ENUM ('Pendiente','Confirmada','Cancelada','Completada');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Facturacion_pago_status_enum') THEN
    CREATE TYPE "Facturacion_pago_status_enum" AS ENUM ('Pendiente','Pagado','Parcial');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Operacion_enum') THEN
    CREATE TYPE "Operacion_enum" AS ENUM ('INSERT','UPDATE','DELETE');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Rol_tipo_enum') THEN
    CREATE TYPE "Rol_tipo_enum" AS ENUM ('empleado','usuario');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Consentimiento_estado_enum') THEN
    CREATE TYPE "Consentimiento_estado_enum" AS ENUM ('Aceptado','Rechazado','Pendiente');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Tipo_pago_enum') THEN
    CREATE TYPE "Tipo_pago_enum" AS ENUM ('Efectivo','Tarjeta','Transferencia','Cheque');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Estado_pedido_enum') THEN
    CREATE TYPE "Estado_pedido_enum" AS ENUM ('Pendiente','Enviado','Recibido','Cancelado');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Cita_tipo_enum') THEN
    CREATE TYPE "Cita_tipo_enum" AS ENUM ('Normal','Urgente','Control');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Cita_prioridad_enum') THEN
    CREATE TYPE "Cita_prioridad_enum" AS ENUM ('Baja','Media','Alta');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Movimiento_stock_tipo_enum') THEN
    CREATE TYPE "Movimiento_stock_tipo_enum" AS ENUM ('Entrada','Salida','Ajuste');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Estado_usuario_enum') THEN
    CREATE TYPE "Estado_usuario_enum" AS ENUM ('activo','inactivo');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Recordatorio_estado_enum') THEN
    CREATE TYPE "Recordatorio_estado_enum" AS ENUM ('Pendiente','Enviado','Fallido');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Dia_semana_enum') THEN
    CREATE TYPE "Dia_semana_enum" AS ENUM ('Lunes','Martes','Miercoles','Jueves','Viernes','Sabado','Domingo');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Tipo_mensaje_enum') THEN
    CREATE TYPE "Tipo_mensaje_enum" AS ENUM ('email','sms');
  END IF;

  -- Nuevo: roles de tenant tipados
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Tenant_role_enum') THEN
    CREATE TYPE "Tenant_role_enum" AS ENUM ('owner','admin','staff','viewer','empleado','manager');
  END IF;
END$$;

-- =========================================================
-- 2) Helpers: updated_at automático
-- =========================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW."updated_at" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

ALTER FUNCTION set_updated_at() OWNER TO app_owner;

-- =========================================================
-- 3) Tablas
-- =========================================================

CREATE TABLE IF NOT EXISTS "Empresas" (
  "id_empresa" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150) NOT NULL,
  "nif" varchar(50),
  "email" varchar(150),
  "telefono" varchar(20),
  "email_recordatorios" varchar(150),
  "telefono_recordatorios" varchar(20),
  "nombre_remitente" varchar(150),
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamptz,
  CONSTRAINT "empresas_deleted_chk"
    CHECK (("deleted"=false AND "deleted_at" IS NULL) OR ("deleted"=true AND "deleted_at" IS NOT NULL)),
  CONSTRAINT "empresas_nombre_chk" CHECK (length(trim("nombre")) > 0)
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_empresas_set_updated_at') THEN
    CREATE TRIGGER "tr_empresas_set_updated_at"
    BEFORE UPDATE ON "Empresas" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Clinicas" (
  "id_clinica" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "nombre" varchar(150) NOT NULL,
  "telefono" varchar(20),
  "email_recordatorios" varchar(150),
  "telefono_recordatorios" varchar(20),
  "nombre_remitente" varchar(150),
  "direccion" varchar(255),
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamptz,
  CONSTRAINT "clinicas_deleted_chk"
    CHECK (("deleted"=false AND "deleted_at" IS NULL) OR ("deleted"=true AND "deleted_at" IS NOT NULL)),
  CONSTRAINT "clinicas_nombre_chk" CHECK (length(trim("nombre")) > 0),
  CONSTRAINT "ux_clinicas_tenant" UNIQUE ("id_empresa","id_clinica")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_clinicas_set_updated_at') THEN
    CREATE TRIGGER "tr_clinicas_set_updated_at"
    BEFORE UPDATE ON "Clinicas" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Roles" (
  "id_role" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_role" varchar(50) NOT NULL,
  "descripcion" varchar(255),
  "tipo" "Rol_tipo_enum" NOT NULL,
  CONSTRAINT "roles_nombre_chk" CHECK (length(trim("nombre_role")) > 0)
);

CREATE TABLE IF NOT EXISTS "Usuarios" (
  "id_usuario" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "apellido" varchar(100) NOT NULL,
  "email" varchar(150) NOT NULL,
  "password" varchar(255) NOT NULL,
  "estado" "Estado_usuario_enum" NOT NULL DEFAULT 'activo',
  "id_role" int NOT NULL,
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamptz,
  CONSTRAINT "usuarios_deleted_chk"
    CHECK (("deleted"=false AND "deleted_at" IS NULL) OR ("deleted"=true AND "deleted_at" IS NOT NULL)),
  CONSTRAINT "usuarios_email_chk" CHECK (length(trim("email")) > 3)
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_usuarios_set_updated_at') THEN
    CREATE TRIGGER "tr_usuarios_set_updated_at"
    BEFORE UPDATE ON "Usuarios" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Usuarios_Empresas" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" int NOT NULL,
  "id_empresa" int NOT NULL,
  "rol" "Tenant_role_enum" NOT NULL,
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ux_usuarios_empresas_usuario_empresa" UNIQUE ("id_usuario","id_empresa")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_usuarios_empresas_set_updated_at') THEN
    CREATE TRIGGER "tr_usuarios_empresas_set_updated_at"
    BEFORE UPDATE ON "Usuarios_Empresas" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Usuarios_Clinicas" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_usuario" int NOT NULL,
  "id_clinica" int NOT NULL,
  "rol" "Tenant_role_enum" NOT NULL,
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ux_usuarios_clinicas_usuario_clinica" UNIQUE ("id_usuario","id_clinica")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_usuarios_clinicas_set_updated_at') THEN
    CREATE TRIGGER "tr_usuarios_clinicas_set_updated_at"
    BEFORE UPDATE ON "Usuarios_Clinicas" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Empleados" (
  "id_empleado" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_clinica" int,
  "id_usuario" int UNIQUE NOT NULL,
  "especialidad" varchar(100),
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ux_empleados_tenant" UNIQUE ("id_empresa","id_empleado")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_empleados_set_updated_at') THEN
    CREATE TRIGGER "tr_empleados_set_updated_at"
    BEFORE UPDATE ON "Empleados" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Pacientes" (
  "id_paciente" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_clinica" int,
  "id_usuario" int UNIQUE,
  "fecha_nacimiento" date,
  "telefono" varchar(20),
  "direccion" varchar(255),
  "historial_medico" text,
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamptz,
  CONSTRAINT "pacientes_deleted_chk"
    CHECK (("deleted"=false AND "deleted_at" IS NULL) OR ("deleted"=true AND "deleted_at" IS NOT NULL)),
  CONSTRAINT "ux_pacientes_tenant" UNIQUE ("id_empresa","id_paciente")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_pacientes_set_updated_at') THEN
    CREATE TRIGGER "tr_pacientes_set_updated_at"
    BEFORE UPDATE ON "Pacientes" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Consentimientos" (
  "id_consentimiento" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_paciente" int NOT NULL,
  "tipo" varchar(100) NOT NULL,
  "estado" "Consentimiento_estado_enum" NOT NULL DEFAULT 'Pendiente',
  "fecha" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "consentimientos_tipo_chk" CHECK (length(trim("tipo")) > 0),
  CONSTRAINT "ux_consentimientos_tenant" UNIQUE ("id_empresa","id_consentimiento")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_consentimientos_set_updated_at') THEN
    CREATE TRIGGER "tr_consentimientos_set_updated_at"
    BEFORE UPDATE ON "Consentimientos" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

-- Citas: añadimos columnas generadas + EXCLUDE para no solapar
CREATE TABLE IF NOT EXISTS "Citas" (
  "id_cita" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_clinica" int,
  "id_paciente" int NOT NULL,
  "id_empleado" int NOT NULL,
  "fecha" date NOT NULL,
  "hora" time NOT NULL,
  "estado" "Citas_estado_enum" NOT NULL DEFAULT 'Pendiente',
  "notas" text,
  "duracion_minutos" int NOT NULL DEFAULT 30,
  "tipo" "Cita_tipo_enum" NOT NULL DEFAULT 'Normal',
  "prioridad" "Cita_prioridad_enum" NOT NULL DEFAULT 'Media',
  "inicio_ts" timestamp GENERATED ALWAYS AS (("fecha" + "hora")) STORED,
  "fin_ts" timestamp GENERATED ALWAYS AS (("fecha" + "hora" + ("duracion_minutos" * interval '1 minute'))) STORED,
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamptz,
  CONSTRAINT "citas_deleted_chk"
    CHECK (("deleted"=false AND "deleted_at" IS NULL) OR ("deleted"=true AND "deleted_at" IS NOT NULL)),
  CONSTRAINT "citas_duracion_chk" CHECK ("duracion_minutos" > 0),
  CONSTRAINT "ux_citas_tenant" UNIQUE ("id_empresa","id_cita"),
  CONSTRAINT "citas_no_solape_excl"
    EXCLUDE USING gist (
      "id_empresa" WITH =,
      "id_empleado" WITH =,
      tsrange("inicio_ts","fin_ts",'[)') WITH &&
    )
    WHERE ("deleted" = false)
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_citas_set_updated_at') THEN
    CREATE TRIGGER "tr_citas_set_updated_at"
    BEFORE UPDATE ON "Citas" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Disponibilidad" (
  "id_disponibilidad" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_clinica" int,
  "id_empleado" int NOT NULL,
  "dia_semana" "Dia_semana_enum" NOT NULL,
  "hora_inicio" time NOT NULL,
  "hora_fin" time NOT NULL,
  "duracion_slot" int NOT NULL DEFAULT 30,
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "disponibilidad_horas_chk" CHECK ("hora_inicio" < "hora_fin"),
  CONSTRAINT "disponibilidad_slot_chk" CHECK ("duracion_slot" > 0),
  CONSTRAINT "ux_disponibilidad_tenant" UNIQUE ("id_empresa","id_disponibilidad")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_disponibilidad_set_updated_at') THEN
    CREATE TRIGGER "tr_disponibilidad_set_updated_at"
    BEFORE UPDATE ON "Disponibilidad" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Historial" (
  "id_historial" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_paciente" int NOT NULL,
  "id_empleado" int NOT NULL,
  "fecha" date NOT NULL,
  "descripcion" text,
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamptz,
  CONSTRAINT "historial_deleted_chk"
    CHECK (("deleted"=false AND "deleted_at" IS NULL) OR ("deleted"=true AND "deleted_at" IS NOT NULL)),
  CONSTRAINT "ux_historial_tenant" UNIQUE ("id_empresa","id_historial")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_historial_set_updated_at') THEN
    CREATE TRIGGER "tr_historial_set_updated_at"
    BEFORE UPDATE ON "Historial" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Documentos" (
  "id_documento" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_historial" int NOT NULL,
  "nombre_archivo" varchar(255),
  "url_archivo" text,
  "tipo_documento" varchar(50),
  "fecha_subida" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamptz,
  CONSTRAINT "documentos_deleted_chk"
    CHECK (("deleted"=false AND "deleted_at" IS NULL) OR ("deleted"=true AND "deleted_at" IS NOT NULL)),
  CONSTRAINT "ux_documentos_tenant" UNIQUE ("id_empresa","id_documento")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_documentos_set_updated_at') THEN
    CREATE TRIGGER "tr_documentos_set_updated_at"
    BEFORE UPDATE ON "Documentos" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Tratamientos" (
  "id_tratamiento" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "nombre_tratamiento" varchar(150) NOT NULL,
  "descripcion" text,
  "unidades" numeric(10,2),
  "precio" numeric(10,2),
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "tratamientos_nombre_chk" CHECK (length(trim("nombre_tratamiento")) > 0),
  CONSTRAINT "tratamientos_unidades_chk" CHECK ("unidades" IS NULL OR "unidades" >= 0),
  CONSTRAINT "tratamientos_precio_chk" CHECK ("precio" IS NULL OR "precio" >= 0),
  CONSTRAINT "ux_tratamientos_tenant" UNIQUE ("id_empresa","id_tratamiento")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_tratamientos_set_updated_at') THEN
    CREATE TRIGGER "tr_tratamientos_set_updated_at"
    BEFORE UPDATE ON "Tratamientos" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Productos" (
  "id_producto" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "nombre_producto" varchar(150) NOT NULL,
  "precio" numeric(10,2),
  "coste" numeric(10,2),
  "vendible" boolean NOT NULL DEFAULT true,
  "stock_actual" int NOT NULL DEFAULT 0,
  "stock_minimo" int NOT NULL DEFAULT 0,
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "productos_nombre_chk" CHECK (length(trim("nombre_producto")) > 0),
  CONSTRAINT "productos_precio_chk" CHECK ("precio" IS NULL OR "precio" >= 0),
  CONSTRAINT "productos_coste_chk" CHECK ("coste" IS NULL OR "coste" >= 0),
  CONSTRAINT "productos_stock_actual_chk" CHECK ("stock_actual" >= 0),
  CONSTRAINT "productos_stock_minimo_chk" CHECK ("stock_minimo" >= 0),
  CONSTRAINT "ux_productos_tenant" UNIQUE ("id_empresa","id_producto")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_productos_set_updated_at') THEN
    CREATE TRIGGER "tr_productos_set_updated_at"
    BEFORE UPDATE ON "Productos" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Productos_Tratamientos" (
  "id_producto_tratamiento" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_producto" int NOT NULL,
  "id_tratamiento" int NOT NULL,
  "unidades" int,
  "consumible" boolean NOT NULL DEFAULT true,
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "productos_tratamientos_unidades_chk" CHECK ("unidades" IS NULL OR "unidades" > 0),
  CONSTRAINT "ux_productos_tratamientos_tenant" UNIQUE ("id_empresa","id_producto","id_tratamiento")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_productos_tratamientos_set_updated_at') THEN
    CREATE TRIGGER "tr_productos_tratamientos_set_updated_at"
    BEFORE UPDATE ON "Productos_Tratamientos" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

-- Mejorada: añade updated_at y trigger (coherencia)
CREATE TABLE IF NOT EXISTS "Productos_Lotes" (
  "id_lote" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_producto" int NOT NULL,
  "numero_lote" varchar(100) NOT NULL,
  "fecha_caducidad" date,
  "stock_lote" int NOT NULL,
  "coste_unitario" numeric(10,2),
  "fecha_entrada" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamptz,
  CONSTRAINT "productos_lotes_deleted_chk"
    CHECK (("deleted"=false AND "deleted_at" IS NULL) OR ("deleted"=true AND "deleted_at" IS NOT NULL)),
  CONSTRAINT "productos_lotes_numero_chk" CHECK (length(trim("numero_lote")) > 0),
  CONSTRAINT "productos_lotes_stock_chk" CHECK ("stock_lote" >= 0),
  CONSTRAINT "productos_lotes_coste_chk" CHECK ("coste_unitario" IS NULL OR "coste_unitario" >= 0),
  CONSTRAINT "ux_productos_lotes_tenant" UNIQUE ("id_empresa","id_lote")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_productos_lotes_set_updated_at') THEN
    CREATE TRIGGER "tr_productos_lotes_set_updated_at"
    BEFORE UPDATE ON "Productos_Lotes" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "MovimientosStock" (
  "id_movimiento" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_clinica" int,
  "id_producto" int NOT NULL,
  "id_lote" int,
  "tipo" "Movimiento_stock_tipo_enum" NOT NULL,
  "cantidad" int NOT NULL,
  "fecha" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "motivo" text,
  "id_usuario" int,
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "movimientos_stock_cantidad_chk" CHECK ("cantidad" > 0),
  CONSTRAINT "ux_movimientos_stock_tenant" UNIQUE ("id_empresa","id_movimiento")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_movimientos_stock_set_updated_at') THEN
    CREATE TRIGGER "tr_movimientos_stock_set_updated_at"
    BEFORE UPDATE ON "MovimientosStock" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Proveedores" (
  "id_proveedor" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "nombre" varchar(150) NOT NULL,
  "contacto" varchar(100),
  "email" varchar(150),
  "telefono" varchar(20),
  "direccion" varchar(255),
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "proveedores_nombre_chk" CHECK (length(trim("nombre")) > 0),
  CONSTRAINT "ux_proveedores_tenant" UNIQUE ("id_empresa","id_proveedor")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_proveedores_set_updated_at') THEN
    CREATE TRIGGER "tr_proveedores_set_updated_at"
    BEFORE UPDATE ON "Proveedores" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "PedidosProveedores" (
  "id_pedido" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_proveedor" int NOT NULL,
  "fecha_pedido" date NOT NULL,
  "fecha_entrega" date,
  "estado" "Estado_pedido_enum" NOT NULL DEFAULT 'Pendiente',
  "total" numeric(10,2),
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "pedidos_total_chk" CHECK ("total" IS NULL OR "total" >= 0),
  CONSTRAINT "pedidos_fechas_chk" CHECK ("fecha_entrega" IS NULL OR "fecha_entrega" >= "fecha_pedido"),
  CONSTRAINT "ux_pedidos_tenant" UNIQUE ("id_empresa","id_pedido")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_pedidos_set_updated_at') THEN
    CREATE TRIGGER "tr_pedidos_set_updated_at"
    BEFORE UPDATE ON "PedidosProveedores" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "PedidoProducto" (
  "id_detalle" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_pedido" int NOT NULL,
  "id_producto" int NOT NULL,
  "cantidad" int NOT NULL,
  "precio_unitario" numeric(10,2),
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "pedido_producto_cantidad_chk" CHECK ("cantidad" > 0),
  CONSTRAINT "pedido_producto_precio_chk" CHECK ("precio_unitario" IS NULL OR "precio_unitario" >= 0),
  CONSTRAINT "ux_pedido_producto_tenant" UNIQUE ("id_empresa","id_pedido","id_producto")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_pedido_producto_set_updated_at') THEN
    CREATE TRIGGER "tr_pedido_producto_set_updated_at"
    BEFORE UPDATE ON "PedidoProducto" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Presupuestos" (
  "id_presupuesto" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_clinica" int,
  "id_paciente" int NOT NULL,
  "id_tratamiento" int,
  "fecha_emision" date NOT NULL,
  "importe_total" numeric(10,2) NOT NULL,
  "descuento" numeric(10,2) NOT NULL DEFAULT 0,
  "estado" "Facturacion_pago_status_enum" NOT NULL DEFAULT 'Pendiente',
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "presupuestos_importe_chk" CHECK ("importe_total" >= 0),
  CONSTRAINT "presupuestos_descuento_chk" CHECK ("descuento" >= 0 AND "descuento" <= "importe_total"),
  CONSTRAINT "ux_presupuestos_tenant" UNIQUE ("id_empresa","id_presupuesto")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_presupuestos_set_updated_at') THEN
    CREATE TRIGGER "tr_presupuestos_set_updated_at"
    BEFORE UPDATE ON "Presupuestos" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Presupuesto_Tratamientos" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_presupuesto" int NOT NULL,
  "id_tratamiento" int NOT NULL,
  "unidades" int NOT NULL DEFAULT 1,
  "precio_unitario" numeric(10,2),
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "pres_trat_unidades_chk" CHECK ("unidades" > 0),
  CONSTRAINT "pres_trat_precio_chk" CHECK ("precio_unitario" IS NULL OR "precio_unitario" >= 0),
  CONSTRAINT "ux_presupuesto_trat_tenant" UNIQUE ("id_empresa","id_presupuesto","id_tratamiento")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_pres_trat_set_updated_at') THEN
    CREATE TRIGGER "tr_pres_trat_set_updated_at"
    BEFORE UPDATE ON "Presupuesto_Tratamientos" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Facturacion" (
  "id_factura" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_clinica" int,
  "id_paciente" int NOT NULL,
  "id_cita" int,
  "id_presupuesto" int,
  "fecha_emision" date NOT NULL,
  "importe_total" numeric(10,2) NOT NULL,
  "descuento" numeric(10,2) NOT NULL DEFAULT 0,
  "pago_status" "Facturacion_pago_status_enum" NOT NULL DEFAULT 'Pendiente',
  "tipo_pago" "Tipo_pago_enum" NOT NULL,
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "facturacion_importe_chk" CHECK ("importe_total" >= 0),
  CONSTRAINT "facturacion_descuento_chk" CHECK ("descuento" >= 0 AND "descuento" <= "importe_total"),
  CONSTRAINT "ux_facturacion_tenant" UNIQUE ("id_empresa","id_factura")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_facturacion_set_updated_at') THEN
    CREATE TRIGGER "tr_facturacion_set_updated_at"
    BEFORE UPDATE ON "Facturacion" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "PagosFactura" (
  "id_pago" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_factura" int NOT NULL,
  "monto" numeric(10,2) NOT NULL,
  "fecha" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "tipo_pago" "Tipo_pago_enum" NOT NULL,
  "id_usuario" int,
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "pagos_factura_monto_chk" CHECK ("monto" > 0)
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_pagos_factura_set_updated_at') THEN
    CREATE TRIGGER "tr_pagos_factura_set_updated_at"
    BEFORE UPDATE ON "PagosFactura" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Factura_Tratamientos" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_factura" int NOT NULL,
  "id_tratamiento" int NOT NULL,
  "unidades" int NOT NULL DEFAULT 1,
  "precio_unitario" numeric(10,2),
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "factura_trat_unidades_chk" CHECK ("unidades" > 0),
  CONSTRAINT "factura_trat_precio_chk" CHECK ("precio_unitario" IS NULL OR "precio_unitario" >= 0),
  CONSTRAINT "ux_factura_trat_tenant" UNIQUE ("id_empresa","id_factura","id_tratamiento")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_factura_trat_set_updated_at') THEN
    CREATE TRIGGER "tr_factura_trat_set_updated_at"
    BEFORE UPDATE ON "Factura_Tratamientos" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Citas_Tratamientos" (
  "id_cita_tratamiento" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_cita" int NOT NULL,
  "id_tratamiento" int NOT NULL,
  "unidades" int NOT NULL DEFAULT 1,
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "citas_trat_unidades_chk" CHECK ("unidades" > 0),
  CONSTRAINT "ux_citas_trat_tenant" UNIQUE ("id_empresa","id_cita","id_tratamiento")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_citas_trat_set_updated_at') THEN
    CREATE TRIGGER "tr_citas_trat_set_updated_at"
    BEFORE UPDATE ON "Citas_Tratamientos" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

-- Mejorada: añade timestamps + unique para evitar duplicados de consumo
CREATE TABLE IF NOT EXISTS "Citas_Productos_Usados" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_cita" int NOT NULL,
  "id_producto" int NOT NULL,
  "id_lote" int NOT NULL,
  "cantidad" int NOT NULL,
  "fecha" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "citas_prod_usados_cantidad_chk" CHECK ("cantidad" > 0),
  CONSTRAINT "ux_citas_prod_usados" UNIQUE ("id_empresa","id_cita","id_producto","id_lote")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_citas_prod_usados_set_updated_at') THEN
    CREATE TRIGGER "tr_citas_prod_usados_set_updated_at"
    BEFORE UPDATE ON "Citas_Productos_Usados" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Notificaciones" (
  "id_notificacion" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_usuario" int NOT NULL,
  "id_paciente" int,
  "titulo" varchar(255) NOT NULL,
  "mensaje" text NOT NULL,
  "leida" boolean NOT NULL DEFAULT false,
  "fecha_envio" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "notificaciones_titulo_chk" CHECK (length(trim("titulo")) > 0)
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_notificaciones_set_updated_at') THEN
    CREATE TRIGGER "tr_notificaciones_set_updated_at"
    BEFORE UPDATE ON "Notificaciones" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Recordatorios" (
  "id_recordatorio" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_cita" int NOT NULL,
  "tipo_mensaje" "Tipo_mensaje_enum" NOT NULL,
  "fecha_envio" timestamptz,
  "estado" "Recordatorio_estado_enum" NOT NULL DEFAULT 'Pendiente',
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_recordatorios_set_updated_at') THEN
    CREATE TRIGGER "tr_recordatorios_set_updated_at"
    BEFORE UPDATE ON "Recordatorios" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Metricas" (
  "id_metricas" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_cita" int,
  "id_paciente" int,
  "id_empleado" int,
  "categoria" varchar(50) NOT NULL,
  "periodo" date NOT NULL,
  "valor" double precision NOT NULL,
  "fecha_creacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "metricas_categoria_chk" CHECK (length(trim("categoria")) > 0)
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'tr_metricas_set_updated_at') THEN
    CREATE TRIGGER "tr_metricas_set_updated_at"
    BEFORE UPDATE ON "Metricas" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "Auditoria" (
  "id_log" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "tabla" varchar(50),
  "id_registro" int,
  "operacion" "Operacion_enum",
  "datos_anteriores" jsonb,
  "datos_nuevos" jsonb,
  "id_usuario" int,
  "fecha" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "AuditoriaConsultas" (
  "id_log" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_usuario" int,
  "tabla_consultada" varchar(50),
  "id_registro_consultado" int,
  "accion" varchar(50),
  "fecha" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "LogsAcceso" (
  "id_log" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_usuario" int NOT NULL,
  "accion" varchar(50) NOT NULL,
  "tabla_afectada" varchar(50),
  "id_registro_afectado" int,
  "ip_origen" varchar(50),
  "user_agent" text,
  "fecha" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "logs_acceso_accion_chk" CHECK (length(trim("accion")) > 0)
);

-- Históricos: FIX 10/10 => FKs compuestas por tenant
CREATE TABLE IF NOT EXISTS "Pacientes_hist" (
  "id_hist" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_paciente" int,
  "nombre" varchar(100),
  "apellido" varchar(100),
  "telefono" varchar(20),
  "direccion" varchar(255),
  "historial_medico" text,
  "fecha_modificacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "id_usuario_modificacion" int
);

CREATE TABLE IF NOT EXISTS "Citas_hist" (
  "id_hist" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empresa" int NOT NULL,
  "id_cita" int,
  "id_paciente" int,
  "id_empleado" int,
  "fecha" date,
  "hora" time,
  "estado" "Citas_estado_enum",
  "notas" text,
  "duracion_minutos" int,
  "tipo" "Cita_tipo_enum",
  "prioridad" "Cita_prioridad_enum",
  "fecha_modificacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "id_usuario_modificacion" int
);

COMMENT ON COLUMN "Pacientes"."historial_medico" IS 'Opcionalmente cifrado';

-- =========================================================
-- 4) Foreign Keys (tenant fuertes)
-- =========================================================
ALTER TABLE "Clinicas"
  DROP CONSTRAINT IF EXISTS "fk_clinicas_empresa",
  ADD CONSTRAINT "fk_clinicas_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "Usuarios"
  DROP CONSTRAINT IF EXISTS "fk_usuarios_roles",
  ADD CONSTRAINT "fk_usuarios_roles"
    FOREIGN KEY ("id_role") REFERENCES "Roles" ("id_role") ON DELETE RESTRICT;

ALTER TABLE "Usuarios_Empresas"
  DROP CONSTRAINT IF EXISTS "fk_ue_usuario",
  ADD CONSTRAINT "fk_ue_usuario"
    FOREIGN KEY ("id_usuario") REFERENCES "Usuarios" ("id_usuario") ON DELETE RESTRICT;

ALTER TABLE "Usuarios_Empresas"
  DROP CONSTRAINT IF EXISTS "fk_ue_empresa",
  ADD CONSTRAINT "fk_ue_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "Usuarios_Clinicas"
  DROP CONSTRAINT IF EXISTS "fk_uc_usuario",
  ADD CONSTRAINT "fk_uc_usuario"
    FOREIGN KEY ("id_usuario") REFERENCES "Usuarios" ("id_usuario") ON DELETE RESTRICT;

ALTER TABLE "Usuarios_Clinicas"
  DROP CONSTRAINT IF EXISTS "fk_uc_clinica_tenant",
  ADD CONSTRAINT "fk_uc_clinica_tenant"
    FOREIGN KEY ("id_empresa","id_clinica") REFERENCES "Clinicas" ("id_empresa","id_clinica") ON DELETE RESTRICT;

ALTER TABLE "Empleados"
  DROP CONSTRAINT IF EXISTS "fk_empleados_empresa",
  ADD CONSTRAINT "fk_empleados_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "Empleados"
  DROP CONSTRAINT IF EXISTS "fk_empleados_usuario",
  ADD CONSTRAINT "fk_empleados_usuario"
    FOREIGN KEY ("id_usuario") REFERENCES "Usuarios" ("id_usuario") ON DELETE RESTRICT;

ALTER TABLE "Empleados"
  DROP CONSTRAINT IF EXISTS "fk_empleados_clinica_tenant",
  ADD CONSTRAINT "fk_empleados_clinica_tenant"
    FOREIGN KEY ("id_empresa","id_clinica") REFERENCES "Clinicas" ("id_empresa","id_clinica") ON DELETE RESTRICT;

ALTER TABLE "Pacientes"
  DROP CONSTRAINT IF EXISTS "fk_pacientes_empresa",
  ADD CONSTRAINT "fk_pacientes_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "Pacientes"
  DROP CONSTRAINT IF EXISTS "fk_pacientes_usuario",
  ADD CONSTRAINT "fk_pacientes_usuario"
    FOREIGN KEY ("id_usuario") REFERENCES "Usuarios" ("id_usuario") ON DELETE SET NULL;

ALTER TABLE "Pacientes"
  DROP CONSTRAINT IF EXISTS "fk_pacientes_clinica_tenant",
  ADD CONSTRAINT "fk_pacientes_clinica_tenant"
    FOREIGN KEY ("id_empresa","id_clinica") REFERENCES "Clinicas" ("id_empresa","id_clinica") ON DELETE RESTRICT;

ALTER TABLE "Consentimientos"
  DROP CONSTRAINT IF EXISTS "fk_consent_empresa",
  ADD CONSTRAINT "fk_consent_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "Consentimientos"
  DROP CONSTRAINT IF EXISTS "fk_consent_paciente_tenant",
  ADD CONSTRAINT "fk_consent_paciente_tenant"
    FOREIGN KEY ("id_empresa","id_paciente") REFERENCES "Pacientes" ("id_empresa","id_paciente") ON DELETE RESTRICT;

ALTER TABLE "Citas"
  DROP CONSTRAINT IF EXISTS "fk_citas_empresa",
  ADD CONSTRAINT "fk_citas_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "Citas"
  DROP CONSTRAINT IF EXISTS "fk_citas_clinica_tenant",
  ADD CONSTRAINT "fk_citas_clinica_tenant"
    FOREIGN KEY ("id_empresa","id_clinica") REFERENCES "Clinicas" ("id_empresa","id_clinica") ON DELETE RESTRICT;

ALTER TABLE "Citas"
  DROP CONSTRAINT IF EXISTS "fk_citas_paciente_tenant",
  ADD CONSTRAINT "fk_citas_paciente_tenant"
    FOREIGN KEY ("id_empresa","id_paciente") REFERENCES "Pacientes" ("id_empresa","id_paciente") ON DELETE RESTRICT;

ALTER TABLE "Citas"
  DROP CONSTRAINT IF EXISTS "fk_citas_empleado_tenant",
  ADD CONSTRAINT "fk_citas_empleado_tenant"
    FOREIGN KEY ("id_empresa","id_empleado") REFERENCES "Empleados" ("id_empresa","id_empleado") ON DELETE RESTRICT;

ALTER TABLE "Disponibilidad"
  DROP CONSTRAINT IF EXISTS "fk_disp_empresa",
  ADD CONSTRAINT "fk_disp_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "Disponibilidad"
  DROP CONSTRAINT IF EXISTS "fk_disp_clinica_tenant",
  ADD CONSTRAINT "fk_disp_clinica_tenant"
    FOREIGN KEY ("id_empresa","id_clinica") REFERENCES "Clinicas" ("id_empresa","id_clinica") ON DELETE RESTRICT;

ALTER TABLE "Disponibilidad"
  DROP CONSTRAINT IF EXISTS "fk_disp_empleado_tenant",
  ADD CONSTRAINT "fk_disp_empleado_tenant"
    FOREIGN KEY ("id_empresa","id_empleado") REFERENCES "Empleados" ("id_empresa","id_empleado") ON DELETE RESTRICT;

ALTER TABLE "Historial"
  DROP CONSTRAINT IF EXISTS "fk_hist_empresa",
  ADD CONSTRAINT "fk_hist_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "Historial"
  DROP CONSTRAINT IF EXISTS "fk_hist_paciente_tenant",
  ADD CONSTRAINT "fk_hist_paciente_tenant"
    FOREIGN KEY ("id_empresa","id_paciente") REFERENCES "Pacientes" ("id_empresa","id_paciente") ON DELETE RESTRICT;

ALTER TABLE "Historial"
  DROP CONSTRAINT IF EXISTS "fk_hist_empleado_tenant",
  ADD CONSTRAINT "fk_hist_empleado_tenant"
    FOREIGN KEY ("id_empresa","id_empleado") REFERENCES "Empleados" ("id_empresa","id_empleado") ON DELETE RESTRICT;

ALTER TABLE "Documentos"
  DROP CONSTRAINT IF EXISTS "fk_doc_empresa",
  ADD CONSTRAINT "fk_doc_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "Documentos"
  DROP CONSTRAINT IF EXISTS "fk_doc_historial_tenant",
  ADD CONSTRAINT "fk_doc_historial_tenant"
    FOREIGN KEY ("id_empresa","id_historial") REFERENCES "Historial" ("id_empresa","id_historial") ON DELETE RESTRICT;

ALTER TABLE "Tratamientos"
  DROP CONSTRAINT IF EXISTS "fk_trat_empresa",
  ADD CONSTRAINT "fk_trat_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "Productos"
  DROP CONSTRAINT IF EXISTS "fk_prod_empresa",
  ADD CONSTRAINT "fk_prod_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "Productos_Tratamientos"
  DROP CONSTRAINT IF EXISTS "fk_pt_empresa",
  ADD CONSTRAINT "fk_pt_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "Productos_Tratamientos"
  DROP CONSTRAINT IF EXISTS "fk_pt_producto_tenant",
  ADD CONSTRAINT "fk_pt_producto_tenant"
    FOREIGN KEY ("id_empresa","id_producto") REFERENCES "Productos" ("id_empresa","id_producto") ON DELETE RESTRICT;

ALTER TABLE "Productos_Tratamientos"
  DROP CONSTRAINT IF EXISTS "fk_pt_tratamiento_tenant",
  ADD CONSTRAINT "fk_pt_tratamiento_tenant"
    FOREIGN KEY ("id_empresa","id_tratamiento") REFERENCES "Tratamientos" ("id_empresa","id_tratamiento") ON DELETE RESTRICT;

ALTER TABLE "Productos_Lotes"
  DROP CONSTRAINT IF EXISTS "fk_lotes_empresa",
  ADD CONSTRAINT "fk_lotes_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "Productos_Lotes"
  DROP CONSTRAINT IF EXISTS "fk_lotes_producto_tenant",
  ADD CONSTRAINT "fk_lotes_producto_tenant"
    FOREIGN KEY ("id_empresa","id_producto") REFERENCES "Productos" ("id_empresa","id_producto") ON DELETE RESTRICT;

ALTER TABLE "MovimientosStock"
  DROP CONSTRAINT IF EXISTS "fk_mov_empresa",
  ADD CONSTRAINT "fk_mov_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "MovimientosStock"
  DROP CONSTRAINT IF EXISTS "fk_mov_clinica_tenant",
  ADD CONSTRAINT "fk_mov_clinica_tenant"
    FOREIGN KEY ("id_empresa","id_clinica") REFERENCES "Clinicas" ("id_empresa","id_clinica") ON DELETE RESTRICT;

ALTER TABLE "MovimientosStock"
  DROP CONSTRAINT IF EXISTS "fk_mov_producto_tenant",
  ADD CONSTRAINT "fk_mov_producto_tenant"
    FOREIGN KEY ("id_empresa","id_producto") REFERENCES "Productos" ("id_empresa","id_producto") ON DELETE RESTRICT;

ALTER TABLE "MovimientosStock"
  DROP CONSTRAINT IF EXISTS "fk_mov_lote_tenant",
  ADD CONSTRAINT "fk_mov_lote_tenant"
    FOREIGN KEY ("id_empresa","id_lote") REFERENCES "Productos_Lotes" ("id_empresa","id_lote") ON DELETE RESTRICT;

ALTER TABLE "MovimientosStock"
  DROP CONSTRAINT IF EXISTS "fk_mov_usuario",
  ADD CONSTRAINT "fk_mov_usuario"
    FOREIGN KEY ("id_usuario") REFERENCES "Usuarios" ("id_usuario") ON DELETE SET NULL;

ALTER TABLE "Proveedores"
  DROP CONSTRAINT IF EXISTS "fk_prov_empresa",
  ADD CONSTRAINT "fk_prov_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "PedidosProveedores"
  DROP CONSTRAINT IF EXISTS "fk_ped_empresa",
  ADD CONSTRAINT "fk_ped_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "PedidosProveedores"
  DROP CONSTRAINT IF EXISTS "fk_ped_proveedor_tenant",
  ADD CONSTRAINT "fk_ped_proveedor_tenant"
    FOREIGN KEY ("id_empresa","id_proveedor") REFERENCES "Proveedores" ("id_empresa","id_proveedor") ON DELETE RESTRICT;

ALTER TABLE "PedidoProducto"
  DROP CONSTRAINT IF EXISTS "fk_pp_empresa",
  ADD CONSTRAINT "fk_pp_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "PedidoProducto"
  DROP CONSTRAINT IF EXISTS "fk_pp_pedido_tenant",
  ADD CONSTRAINT "fk_pp_pedido_tenant"
    FOREIGN KEY ("id_empresa","id_pedido") REFERENCES "PedidosProveedores" ("id_empresa","id_pedido") ON DELETE RESTRICT;

ALTER TABLE "PedidoProducto"
  DROP CONSTRAINT IF EXISTS "fk_pp_producto_tenant",
  ADD CONSTRAINT "fk_pp_producto_tenant"
    FOREIGN KEY ("id_empresa","id_producto") REFERENCES "Productos" ("id_empresa","id_producto") ON DELETE RESTRICT;

ALTER TABLE "Presupuestos"
  DROP CONSTRAINT IF EXISTS "fk_pres_empresa",
  ADD CONSTRAINT "fk_pres_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "Presupuestos"
  DROP CONSTRAINT IF EXISTS "fk_pres_clinica_tenant",
  ADD CONSTRAINT "fk_pres_clinica_tenant"
    FOREIGN KEY ("id_empresa","id_clinica") REFERENCES "Clinicas" ("id_empresa","id_clinica") ON DELETE RESTRICT;

ALTER TABLE "Presupuestos"
  DROP CONSTRAINT IF EXISTS "fk_pres_paciente_tenant",
  ADD CONSTRAINT "fk_pres_paciente_tenant"
    FOREIGN KEY ("id_empresa","id_paciente") REFERENCES "Pacientes" ("id_empresa","id_paciente") ON DELETE RESTRICT;

ALTER TABLE "Presupuestos"
  DROP CONSTRAINT IF EXISTS "fk_pres_tratamiento_tenant",
  ADD CONSTRAINT "fk_pres_tratamiento_tenant"
    FOREIGN KEY ("id_empresa","id_tratamiento") REFERENCES "Tratamientos" ("id_empresa","id_tratamiento") ON DELETE SET NULL;

ALTER TABLE "Presupuesto_Tratamientos"
  DROP CONSTRAINT IF EXISTS "fk_prest_presupuesto_tenant",
  ADD CONSTRAINT "fk_prest_presupuesto_tenant"
    FOREIGN KEY ("id_empresa","id_presupuesto") REFERENCES "Presupuestos" ("id_empresa","id_presupuesto") ON DELETE RESTRICT;

ALTER TABLE "Presupuesto_Tratamientos"
  DROP CONSTRAINT IF EXISTS "fk_prest_tratamiento_tenant",
  ADD CONSTRAINT "fk_prest_tratamiento_tenant"
    FOREIGN KEY ("id_empresa","id_tratamiento") REFERENCES "Tratamientos" ("id_empresa","id_tratamiento") ON DELETE RESTRICT;

ALTER TABLE "Facturacion"
  DROP CONSTRAINT IF EXISTS "fk_fact_empresa",
  ADD CONSTRAINT "fk_fact_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "Facturacion"
  DROP CONSTRAINT IF EXISTS "fk_fact_clinica_tenant",
  ADD CONSTRAINT "fk_fact_clinica_tenant"
    FOREIGN KEY ("id_empresa","id_clinica") REFERENCES "Clinicas" ("id_empresa","id_clinica") ON DELETE RESTRICT;

ALTER TABLE "Facturacion"
  DROP CONSTRAINT IF EXISTS "fk_fact_paciente_tenant",
  ADD CONSTRAINT "fk_fact_paciente_tenant"
    FOREIGN KEY ("id_empresa","id_paciente") REFERENCES "Pacientes" ("id_empresa","id_paciente") ON DELETE RESTRICT;

ALTER TABLE "Facturacion"
  DROP CONSTRAINT IF EXISTS "fk_fact_cita_tenant",
  ADD CONSTRAINT "fk_fact_cita_tenant"
    FOREIGN KEY ("id_empresa","id_cita") REFERENCES "Citas" ("id_empresa","id_cita") ON DELETE RESTRICT;

ALTER TABLE "Facturacion"
  DROP CONSTRAINT IF EXISTS "fk_fact_presupuesto_tenant",
  ADD CONSTRAINT "fk_fact_presupuesto_tenant"
    FOREIGN KEY ("id_empresa","id_presupuesto") REFERENCES "Presupuestos" ("id_empresa","id_presupuesto") ON DELETE RESTRICT;

ALTER TABLE "PagosFactura"
  DROP CONSTRAINT IF EXISTS "fk_pago_factura_tenant",
  ADD CONSTRAINT "fk_pago_factura_tenant"
    FOREIGN KEY ("id_empresa","id_factura") REFERENCES "Facturacion" ("id_empresa","id_factura") ON DELETE RESTRICT;

ALTER TABLE "PagosFactura"
  DROP CONSTRAINT IF EXISTS "fk_pago_usuario",
  ADD CONSTRAINT "fk_pago_usuario"
    FOREIGN KEY ("id_usuario") REFERENCES "Usuarios" ("id_usuario") ON DELETE SET NULL;

ALTER TABLE "Factura_Tratamientos"
  DROP CONSTRAINT IF EXISTS "fk_ft_factura_tenant",
  ADD CONSTRAINT "fk_ft_factura_tenant"
    FOREIGN KEY ("id_empresa","id_factura") REFERENCES "Facturacion" ("id_empresa","id_factura") ON DELETE RESTRICT;

ALTER TABLE "Factura_Tratamientos"
  DROP CONSTRAINT IF EXISTS "fk_ft_tratamiento_tenant",
  ADD CONSTRAINT "fk_ft_tratamiento_tenant"
    FOREIGN KEY ("id_empresa","id_tratamiento") REFERENCES "Tratamientos" ("id_empresa","id_tratamiento") ON DELETE RESTRICT;

ALTER TABLE "Citas_Tratamientos"
  DROP CONSTRAINT IF EXISTS "fk_ct_cita_tenant",
  ADD CONSTRAINT "fk_ct_cita_tenant"
    FOREIGN KEY ("id_empresa","id_cita") REFERENCES "Citas" ("id_empresa","id_cita") ON DELETE RESTRICT;

ALTER TABLE "Citas_Tratamientos"
  DROP CONSTRAINT IF EXISTS "fk_ct_tratamiento_tenant",
  ADD CONSTRAINT "fk_ct_tratamiento_tenant"
    FOREIGN KEY ("id_empresa","id_tratamiento") REFERENCES "Tratamientos" ("id_empresa","id_tratamiento") ON DELETE RESTRICT;

ALTER TABLE "Citas_Productos_Usados"
  DROP CONSTRAINT IF EXISTS "fk_cpu_cita_tenant",
  ADD CONSTRAINT "fk_cpu_cita_tenant"
    FOREIGN KEY ("id_empresa","id_cita") REFERENCES "Citas" ("id_empresa","id_cita") ON DELETE RESTRICT;

ALTER TABLE "Citas_Productos_Usados"
  DROP CONSTRAINT IF EXISTS "fk_cpu_producto_tenant",
  ADD CONSTRAINT "fk_cpu_producto_tenant"
    FOREIGN KEY ("id_empresa","id_producto") REFERENCES "Productos" ("id_empresa","id_producto") ON DELETE RESTRICT;

ALTER TABLE "Citas_Productos_Usados"
  DROP CONSTRAINT IF EXISTS "fk_cpu_lote_tenant",
  ADD CONSTRAINT "fk_cpu_lote_tenant"
    FOREIGN KEY ("id_empresa","id_lote") REFERENCES "Productos_Lotes" ("id_empresa","id_lote") ON DELETE RESTRICT;

ALTER TABLE "Notificaciones"
  DROP CONSTRAINT IF EXISTS "fk_notif_empresa",
  ADD CONSTRAINT "fk_notif_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "Notificaciones"
  DROP CONSTRAINT IF EXISTS "fk_notif_usuario",
  ADD CONSTRAINT "fk_notif_usuario"
    FOREIGN KEY ("id_usuario") REFERENCES "Usuarios" ("id_usuario") ON DELETE RESTRICT;

ALTER TABLE "Notificaciones"
  DROP CONSTRAINT IF EXISTS "fk_notif_paciente_tenant",
  ADD CONSTRAINT "fk_notif_paciente_tenant"
    FOREIGN KEY ("id_empresa","id_paciente") REFERENCES "Pacientes" ("id_empresa","id_paciente") ON DELETE SET NULL;

ALTER TABLE "Recordatorios"
  DROP CONSTRAINT IF EXISTS "fk_rec_cita_tenant",
  ADD CONSTRAINT "fk_rec_cita_tenant"
    FOREIGN KEY ("id_empresa","id_cita") REFERENCES "Citas" ("id_empresa","id_cita") ON DELETE RESTRICT;

ALTER TABLE "Metricas"
  DROP CONSTRAINT IF EXISTS "fk_met_cita_tenant",
  ADD CONSTRAINT "fk_met_cita_tenant"
    FOREIGN KEY ("id_empresa","id_cita") REFERENCES "Citas" ("id_empresa","id_cita") ON DELETE SET NULL;

ALTER TABLE "Metricas"
  DROP CONSTRAINT IF EXISTS "fk_met_paciente_tenant",
  ADD CONSTRAINT "fk_met_paciente_tenant"
    FOREIGN KEY ("id_empresa","id_paciente") REFERENCES "Pacientes" ("id_empresa","id_paciente") ON DELETE SET NULL;

ALTER TABLE "Metricas"
  DROP CONSTRAINT IF EXISTS "fk_met_empleado_tenant",
  ADD CONSTRAINT "fk_met_empleado_tenant"
    FOREIGN KEY ("id_empresa","id_empleado") REFERENCES "Empleados" ("id_empresa","id_empleado") ON DELETE SET NULL;

ALTER TABLE "Auditoria"
  DROP CONSTRAINT IF EXISTS "fk_aud_empresa",
  ADD CONSTRAINT "fk_aud_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "Auditoria"
  DROP CONSTRAINT IF EXISTS "fk_aud_usuario",
  ADD CONSTRAINT "fk_aud_usuario"
    FOREIGN KEY ("id_usuario") REFERENCES "Usuarios" ("id_usuario") ON DELETE SET NULL;

ALTER TABLE "AuditoriaConsultas"
  DROP CONSTRAINT IF EXISTS "fk_audc_empresa",
  ADD CONSTRAINT "fk_audc_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "AuditoriaConsultas"
  DROP CONSTRAINT IF EXISTS "fk_audc_usuario",
  ADD CONSTRAINT "fk_audc_usuario"
    FOREIGN KEY ("id_usuario") REFERENCES "Usuarios" ("id_usuario") ON DELETE SET NULL;

ALTER TABLE "LogsAcceso"
  DROP CONSTRAINT IF EXISTS "fk_logs_empresa",
  ADD CONSTRAINT "fk_logs_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "LogsAcceso"
  DROP CONSTRAINT IF EXISTS "fk_logs_usuario",
  ADD CONSTRAINT "fk_logs_usuario"
    FOREIGN KEY ("id_usuario") REFERENCES "Usuarios" ("id_usuario") ON DELETE RESTRICT;

-- Históricos: FIX (FK compuesta)
ALTER TABLE "Pacientes_hist"
  DROP CONSTRAINT IF EXISTS "fk_ph_empresa",
  ADD CONSTRAINT "fk_ph_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "Pacientes_hist"
  DROP CONSTRAINT IF EXISTS "fk_ph_paciente_tenant",
  ADD CONSTRAINT "fk_ph_paciente_tenant"
    FOREIGN KEY ("id_empresa","id_paciente") REFERENCES "Pacientes" ("id_empresa","id_paciente") ON DELETE SET NULL;

ALTER TABLE "Pacientes_hist"
  DROP CONSTRAINT IF EXISTS "fk_ph_usuario",
  ADD CONSTRAINT "fk_ph_usuario"
    FOREIGN KEY ("id_usuario_modificacion") REFERENCES "Usuarios" ("id_usuario") ON DELETE SET NULL;

ALTER TABLE "Citas_hist"
  DROP CONSTRAINT IF EXISTS "fk_ch_empresa",
  ADD CONSTRAINT "fk_ch_empresa"
    FOREIGN KEY ("id_empresa") REFERENCES "Empresas" ("id_empresa") ON DELETE RESTRICT;

ALTER TABLE "Citas_hist"
  DROP CONSTRAINT IF EXISTS "fk_ch_cita_tenant",
  ADD CONSTRAINT "fk_ch_cita_tenant"
    FOREIGN KEY ("id_empresa","id_cita") REFERENCES "Citas" ("id_empresa","id_cita") ON DELETE SET NULL;

ALTER TABLE "Citas_hist"
  DROP CONSTRAINT IF EXISTS "fk_ch_paciente_tenant",
  ADD CONSTRAINT "fk_ch_paciente_tenant"
    FOREIGN KEY ("id_empresa","id_paciente") REFERENCES "Pacientes" ("id_empresa","id_paciente") ON DELETE SET NULL;

ALTER TABLE "Citas_hist"
  DROP CONSTRAINT IF EXISTS "fk_ch_empleado_tenant",
  ADD CONSTRAINT "fk_ch_empleado_tenant"
    FOREIGN KEY ("id_empresa","id_empleado") REFERENCES "Empleados" ("id_empresa","id_empleado") ON DELETE SET NULL;

ALTER TABLE "Citas_hist"
  DROP CONSTRAINT IF EXISTS "fk_ch_usuario",
  ADD CONSTRAINT "fk_ch_usuario"
    FOREIGN KEY ("id_usuario_modificacion") REFERENCES "Usuarios" ("id_usuario") ON DELETE SET NULL;

-- =========================================================
-- 5) Índices (soft-delete + performance)
-- =========================================================
CREATE UNIQUE INDEX IF NOT EXISTS "ux_clinicas_empresa_nombre_alive"
  ON "Clinicas" ("id_empresa","nombre")
  WHERE "deleted" = false;

CREATE UNIQUE INDEX IF NOT EXISTS "ux_usuarios_email_alive_ci"
  ON "Usuarios" (lower("email"))
  WHERE "deleted" = false;

-- Este sigue siendo útil (además del EXCLUDE) para queries por slot exacto
CREATE UNIQUE INDEX IF NOT EXISTS "ux_citas_slot_alive"
  ON "Citas" ("id_empresa","id_empleado","fecha","hora")
  WHERE "deleted" = false;

CREATE UNIQUE INDEX IF NOT EXISTS "ux_lotes_producto_numero_alive"
  ON "Productos_Lotes" ("id_empresa","id_producto","numero_lote")
  WHERE "deleted" = false;

CREATE UNIQUE INDEX IF NOT EXISTS "ux_facturacion_cita_notnull"
  ON "Facturacion" ("id_empresa","id_cita")
  WHERE "id_cita" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "ix_ue_usuario" ON "Usuarios_Empresas" ("id_usuario");
CREATE INDEX IF NOT EXISTS "ix_ue_empresa" ON "Usuarios_Empresas" ("id_empresa");

CREATE INDEX IF NOT EXISTS "ix_empleados_empresa" ON "Empleados" ("id_empresa");
CREATE INDEX IF NOT EXISTS "ix_empleados_clinica" ON "Empleados" ("id_clinica");

CREATE INDEX IF NOT EXISTS "ix_pacientes_empresa_telefono" ON "Pacientes" ("id_empresa","telefono");
CREATE INDEX IF NOT EXISTS "ix_pacientes_clinica" ON "Pacientes" ("id_clinica");

CREATE INDEX IF NOT EXISTS "ix_consentimientos_empresa" ON "Consentimientos" ("id_empresa");
CREATE INDEX IF NOT EXISTS "ix_consentimientos_paciente" ON "Consentimientos" ("id_paciente");

CREATE INDEX IF NOT EXISTS "ix_citas_empresa_paciente_fecha" ON "Citas" ("id_empresa","id_paciente","fecha");
CREATE INDEX IF NOT EXISTS "ix_citas_empresa_empleado_fecha" ON "Citas" ("id_empresa","id_empleado","fecha");
CREATE INDEX IF NOT EXISTS "ix_citas_clinica" ON "Citas" ("id_clinica");

CREATE INDEX IF NOT EXISTS "ix_historial_empresa_paciente_fecha" ON "Historial" ("id_empresa","id_paciente","fecha");
CREATE INDEX IF NOT EXISTS "ix_documentos_historial" ON "Documentos" ("id_historial");

CREATE INDEX IF NOT EXISTS "ix_tratamientos_empresa_nombre" ON "Tratamientos" ("id_empresa","nombre_tratamiento");
CREATE INDEX IF NOT EXISTS "ix_productos_empresa_nombre" ON "Productos" ("id_empresa","nombre_producto");

-- Mejorados: índices tenant-first para stock
CREATE INDEX IF NOT EXISTS "ix_mov_stock_empresa" ON "MovimientosStock" ("id_empresa");
CREATE INDEX IF NOT EXISTS "ix_mov_stock_tenant_producto_fecha" ON "MovimientosStock" ("id_empresa","id_producto","fecha");
CREATE INDEX IF NOT EXISTS "ix_mov_stock_tenant_lote_fecha" ON "MovimientosStock" ("id_empresa","id_lote","fecha");

CREATE INDEX IF NOT EXISTS "ix_metricas_empresa_categoria_periodo" ON "Metricas" ("id_empresa","categoria","periodo");

-- =========================================================
-- 6) Permisos y default privileges
-- =========================================================
GRANT SELECT ON "Roles" TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_user;

ALTER DEFAULT PRIVILEGES FOR ROLE app_owner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;

ALTER DEFAULT PRIVILEGES FOR ROLE app_owner IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO app_user;

-- =========================================================
-- 7) RLS (Row Level Security) sin recursión peligrosa
-- =========================================================

-- 7.1 Variables de sesión
CREATE OR REPLACE FUNCTION app_current_user_id()
RETURNS int
LANGUAGE sql
STABLE
AS $$
  SELECT NULLIF(current_setting('app.user_id', true), '')::int
$$;

CREATE OR REPLACE FUNCTION app_current_tenant_id()
RETURNS int
LANGUAGE sql
STABLE
AS $$
  SELECT NULLIF(current_setting('app.tenant_id', true), '')::int
$$;

CREATE OR REPLACE FUNCTION app_has_tenant_context()
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT app_current_user_id() IS NOT NULL AND app_current_tenant_id() IS NOT NULL
$$;

ALTER FUNCTION app_current_user_id() OWNER TO app_owner;
ALTER FUNCTION app_current_tenant_id() OWNER TO app_owner;
ALTER FUNCTION app_has_tenant_context() OWNER TO app_owner;

-- 7.2 Membership: SECURITY DEFINER + row_security=off (evita recursión RLS)
CREATE OR REPLACE FUNCTION app_user_belongs_to_tenant()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
SET row_security = off
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM "Usuarios_Empresas" ue
    WHERE ue."id_usuario" = app_current_user_id()
      AND ue."id_empresa" = app_current_tenant_id()
  )
$$;

CREATE OR REPLACE FUNCTION app_tenant_role()
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
SET row_security = off
AS $$
  SELECT ue."rol"::text
  FROM "Usuarios_Empresas" ue
  WHERE ue."id_usuario" = app_current_user_id()
    AND ue."id_empresa" = app_current_tenant_id()
$$;

CREATE OR REPLACE FUNCTION app_user_can_write_in_tenant()
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT app_user_belongs_to_tenant()
     AND lower(coalesce(app_tenant_role(), '')) IN ('owner','admin','staff','empleado','manager')
$$;

-- El owner de estas funciones debe poder bypass RLS
ALTER FUNCTION app_user_belongs_to_tenant() OWNER TO app_rls;
ALTER FUNCTION app_tenant_role() OWNER TO app_rls;
ALTER FUNCTION app_user_can_write_in_tenant() OWNER TO app_owner;

REVOKE ALL ON FUNCTION app_user_belongs_to_tenant() FROM PUBLIC;
REVOKE ALL ON FUNCTION app_tenant_role() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app_user_belongs_to_tenant() TO app_user;
GRANT EXECUTE ON FUNCTION app_tenant_role() TO app_user;
GRANT EXECUTE ON FUNCTION app_user_can_write_in_tenant() TO app_user;

-- 7.3 RLS: Roles (catálogo)
ALTER TABLE "Roles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Roles" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS roles_select ON "Roles";
CREATE POLICY roles_select ON "Roles" FOR SELECT TO app_user USING (true);

-- 7.4 RLS: Usuarios (solo self)
ALTER TABLE "Usuarios" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Usuarios" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS usuarios_select_self ON "Usuarios";
CREATE POLICY usuarios_select_self
ON "Usuarios" FOR SELECT TO app_user
USING (app_current_user_id() IS NOT NULL AND "id_usuario" = app_current_user_id());

DROP POLICY IF EXISTS usuarios_update_self ON "Usuarios";
CREATE POLICY usuarios_update_self
ON "Usuarios" FOR UPDATE TO app_user
USING (app_current_user_id() IS NOT NULL AND "id_usuario" = app_current_user_id())
WITH CHECK (app_current_user_id() IS NOT NULL AND "id_usuario" = app_current_user_id());

-- 7.5 RLS: Empresas (solo empresas donde hay membership; usando SECURITY DEFINER)
ALTER TABLE "Empresas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Empresas" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS empresas_select ON "Empresas";
CREATE POLICY empresas_select
ON "Empresas" FOR SELECT TO app_user
USING (
  app_has_tenant_context()
  AND app_user_belongs_to_tenant()
  AND "Empresas"."id_empresa" = app_current_tenant_id()
);

-- 7.6 RLS: Usuarios_Empresas (políticas sin subqueries auto-referenciales con RLS)
ALTER TABLE "Usuarios_Empresas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Usuarios_Empresas" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS ue_select ON "Usuarios_Empresas";
CREATE POLICY ue_select
ON "Usuarios_Empresas" FOR SELECT TO app_user
USING (
  app_current_user_id() IS NOT NULL
  AND (
    "Usuarios_Empresas"."id_usuario" = app_current_user_id()
    OR (
      app_has_tenant_context()
      AND app_user_can_write_in_tenant()
      AND "Usuarios_Empresas"."id_empresa" = app_current_tenant_id()
    )
  )
);

DROP POLICY IF EXISTS ue_insert ON "Usuarios_Empresas";
CREATE POLICY ue_insert
ON "Usuarios_Empresas" FOR INSERT TO app_user
WITH CHECK (app_has_tenant_context() AND app_user_can_write_in_tenant() AND "id_empresa" = app_current_tenant_id());

DROP POLICY IF EXISTS ue_update ON "Usuarios_Empresas";
CREATE POLICY ue_update
ON "Usuarios_Empresas" FOR UPDATE TO app_user
USING (app_has_tenant_context() AND app_user_can_write_in_tenant() AND "id_empresa" = app_current_tenant_id())
WITH CHECK (app_has_tenant_context() AND app_user_can_write_in_tenant() AND "id_empresa" = app_current_tenant_id());

DROP POLICY IF EXISTS ue_delete ON "Usuarios_Empresas";
CREATE POLICY ue_delete
ON "Usuarios_Empresas" FOR DELETE TO app_user
USING (app_has_tenant_context() AND app_user_can_write_in_tenant() AND "id_empresa" = app_current_tenant_id());

-- 7.7 RLS genérico para tenant tables (id_empresa NOT NULL)
DO $$
DECLARE
  t text;
  tenant_tables text[] := ARRAY[
    'Clinicas',
    'Usuarios_Clinicas',
    'Empleados',
    'Pacientes',
    'Consentimientos',
    'Citas',
    'Disponibilidad',
    'Historial',
    'Documentos',
    'Tratamientos',
    'Productos',
    'Productos_Tratamientos',
    'Productos_Lotes',
    'MovimientosStock',
    'Proveedores',
    'PedidosProveedores',
    'PedidoProducto',
    'Presupuestos',
    'Presupuesto_Tratamientos',
    'Facturacion',
    'PagosFactura',
    'Factura_Tratamientos',
    'Citas_Tratamientos',
    'Citas_Productos_Usados',
    'Notificaciones',
    'Recordatorios',
    'Metricas',
    'Auditoria',
    'AuditoriaConsultas',
    'LogsAcceso',
    'Pacientes_hist',
    'Citas_hist'
  ];
BEGIN
  FOREACH t IN ARRAY tenant_tables LOOP
    EXECUTE format('ALTER TABLE "%s" ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('ALTER TABLE "%s" FORCE ROW LEVEL SECURITY;', t);

    EXECUTE format('DROP POLICY IF EXISTS tenant_select ON "%s";', t);
    EXECUTE format(
      'CREATE POLICY tenant_select ON "%s" FOR SELECT TO app_user USING (app_has_tenant_context() AND app_user_belongs_to_tenant() AND "%s"."id_empresa" = app_current_tenant_id());',
      t, t
    );

    EXECUTE format('DROP POLICY IF EXISTS tenant_insert ON "%s";', t);
    EXECUTE format(
      'CREATE POLICY tenant_insert ON "%s" FOR INSERT TO app_user WITH CHECK (app_has_tenant_context() AND app_user_can_write_in_tenant() AND "%s"."id_empresa" = app_current_tenant_id());',
      t, t
    );

    EXECUTE format('DROP POLICY IF EXISTS tenant_update ON "%s";', t);
    EXECUTE format(
      'CREATE POLICY tenant_update ON "%s" FOR UPDATE TO app_user USING (app_has_tenant_context() AND app_user_can_write_in_tenant() AND "%s"."id_empresa" = app_current_tenant_id()) WITH CHECK (app_has_tenant_context() AND app_user_can_write_in_tenant() AND "%s"."id_empresa" = app_current_tenant_id());',
      t, t, t
    );

    EXECUTE format('DROP POLICY IF EXISTS tenant_delete ON "%s";', t);
    EXECUTE format(
      'CREATE POLICY tenant_delete ON "%s" FOR DELETE TO app_user USING (app_has_tenant_context() AND app_user_can_write_in_tenant() AND "%s"."id_empresa" = app_current_tenant_id());',
      t, t
    );
  END LOOP;
END$$;

-- =========================================================
-- 8) Ownership (opcional recomendado en prod)
-- =========================================================
-- ALTER TABLE ... OWNER TO app_owner;
-- ALTER SEQUENCE ... OWNER TO app_owner;

COMMIT;

-- =========================================================
-- USO (backend):
--   SET ROLE app_user;
--   SELECT set_config('app.user_id','123', true);
--   SELECT set_config('app.tenant_id','45', true);
-- =========================================================

-- =========================================================
-- 9) Default Data (Railway Setup)
-- =========================================================
-- Transaction for default data
BEGIN;

DO $$
DECLARE
    role_id int;
    empresa_id int;
    clinica_id int;
    user_id int;
    -- Password used: 'password' (standard Laravel hash) or similar known hash.
    -- Users can reset it.
    -- Using $2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi for 'password'
    user_hashed_pass varchar := '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi'; 
BEGIN
    -- 1. Create Role 'superadmin' if not exists
    INSERT INTO "Roles" ("nombre_role", "descripcion", "tipo")
    VALUES ('superadmin', 'Super Administrator', 'empleado')
    ON CONFLICT DO NOTHING;

    SELECT "id_role" INTO role_id FROM "Roles" WHERE "nombre_role" = 'superadmin';

    -- 2. Create Company 'DentalMate HQ'
    INSERT INTO "Empresas" ("nombre", "nif", "email", "telefono")
    VALUES ('DentalMate HQ', 'A12345678', 'info@dentalmate.com', '+34 900 123 456')
    ON CONFLICT DO NOTHING;

    SELECT "id_empresa" INTO empresa_id FROM "Empresas" WHERE "nombre" = 'DentalMate HQ';

    -- 3. Create Clinic 'Clínica Central'
    INSERT INTO "Clinicas" ("id_empresa", "nombre", "telefono", "direccion")
    VALUES (empresa_id, 'Clínica Central', '+34 900 123 456', 'Calle Principal, 123, Madrid')
    ON CONFLICT ("id_empresa", "nombre") DO NOTHING;

    SELECT "id_clinica" INTO clinica_id FROM "Clinicas" WHERE "nombre" = 'Clínica Central' AND "id_empresa" = empresa_id;

    -- 4. Create User 'Super Admin'
    -- Note: 'id_role' is FK to Roles.
    INSERT INTO "Usuarios" ("nombre", "apellido", "email", "password", "estado", "id_role")
    VALUES ('Super', 'Admin', 'admin@dentalmate.com', user_hashed_pass, 'activo', role_id)
    ON CONFLICT DO NOTHING;

    SELECT "id_usuario" INTO user_id FROM "Usuarios" WHERE "email" = 'admin@dentalmate.com';

    -- 5. Associate User to Company (Owner)
    INSERT INTO "Usuarios_Empresas" ("id_usuario", "id_empresa", "rol")
    VALUES (user_id, empresa_id, 'owner')
    ON CONFLICT ("id_usuario", "id_empresa") DO NOTHING;

    -- 6. Associate User to Clinic (Owner)
    INSERT INTO "Usuarios_Clinicas" ("id_empresa", "id_usuario", "id_clinica", "rol")
    VALUES (empresa_id, user_id, clinica_id, 'owner')
    ON CONFLICT ("id_usuario", "id_clinica") DO NOTHING;

    -- 7. Create Employee Record
    INSERT INTO "Empleados" ("id_empresa", "id_clinica", "id_usuario", "especialidad")
    VALUES (empresa_id, clinica_id, user_id, 'Administración')
    ON CONFLICT ("id_usuario") DO NOTHING;

END $$;

COMMIT;
