
-- https://dbdocs.io/profesionalemailame/DentalMate


CREATE TYPE "Citas_estado_enum" AS ENUM (
  'Pendiente',
  'Confirmada',
  'Cancelada',
  'Completada'
);

CREATE TYPE "Facturacion_pago_status_enum" AS ENUM (
  'Pendiente',
  'Pagado',
  'Parcial'
);

CREATE TABLE "Roles" (
  "id_role" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_role" "VARCHAR(50)" NOT NULL,
  "descripcion" "VARCHAR(255)"
);

CREATE TABLE "Usuarios" (
  "id_usuario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" "VARCHAR(100)" NOT NULL,
  "apellido" "VARCHAR(100)" NOT NULL,
  "email" "VARCHAR(150)" UNIQUE NOT NULL,
  "password" "VARCHAR(255)" NOT NULL,
  "id_role" INT NOT NULL,
  "fecha_creacion" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "Pacientes" (
  "id_paciente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" INT UNIQUE,
  "fecha_nacimiento" DATE,
  "telefono" "VARCHAR(20)",
  "direccion" "VARCHAR(255)",
  "historial_medico" TEXT,
  "fecha_registro" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "Citas" (
  "id_cita" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_paciente" INT NOT NULL,
  "id_dentista" INT NOT NULL,
  "fecha" DATE NOT NULL,
  "hora" TIME NOT NULL,
  "estado" "Citas_estado_enum" DEFAULT 'Pendiente',
  "notas" TEXT
);

CREATE TABLE "Historial" (
  "id_historial" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_paciente" INT NOT NULL,
  "id_dentista" INT NOT NULL,
  "fecha" DATE NOT NULL,
  "descripcion" TEXT,
  "documentos" TEXT
);

CREATE TABLE "Tratamientos" (
  "id_tratamiento" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_tratamiento" TEXT,
  "descripcion" TEXT,
  "unidades" "DOUBLE",
  "precio" "DOUBLE"
);

CREATE TABLE "Facturacion" (
  "id_factura" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_tratamiento" INT NOT NULL,
  "fecha_emision" DATE NOT NULL,
  "monto" "DECIMAL(10,2)" NOT NULL,
  "descuento" "DECIMAL(10,2)" DEFAULT 0,
  "pago_status" "Facturacion_pago_status_enum" DEFAULT 'Pendiente'
);

CREATE TABLE "Productos" (
  "id_producto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_producto" TEXT,
  "precio" "DOUBLE",
  "coste" "DOUBLE"
);

CREATE TABLE "Productos_Tratamientos" (
  "id_Productos_Tratamientos" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" INT NOT NULL,
  "id_tratamiento" INT NOT NULL,
  "unidades" INT
);

ALTER TABLE "Usuarios" ADD FOREIGN KEY ("id_role") REFERENCES "Roles" ("id_role");

ALTER TABLE "Pacientes" ADD FOREIGN KEY ("id_usuario") REFERENCES "Usuarios" ("id_usuario");

ALTER TABLE "Citas" ADD FOREIGN KEY ("id_paciente") REFERENCES "Pacientes" ("id_paciente");

ALTER TABLE "Citas" ADD FOREIGN KEY ("id_dentista") REFERENCES "Usuarios" ("id_usuario");

ALTER TABLE "Historial" ADD FOREIGN KEY ("id_paciente") REFERENCES "Pacientes" ("id_paciente");

ALTER TABLE "Historial" ADD FOREIGN KEY ("id_dentista") REFERENCES "Usuarios" ("id_usuario");

ALTER TABLE "Facturacion" ADD FOREIGN KEY ("id_tratamiento") REFERENCES "Tratamientos" ("id_tratamiento");

ALTER TABLE "Productos_Tratamientos" ADD FOREIGN KEY ("id_producto") REFERENCES "Productos" ("id_producto");

ALTER TABLE "Productos_Tratamientos" ADD FOREIGN KEY ("id_tratamiento") REFERENCES "Tratamientos" ("id_tratamiento");
