-- Adminer 5.4.1 PostgreSQL 16.11 dump

DROP TABLE IF EXISTS "Citas";
CREATE TABLE "public"."Citas" (
    "id_cita" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_clinica" integer,
    "id_paciente" integer NOT NULL,
    "id_empleado" integer NOT NULL,
    "fecha" date NOT NULL,
    "hora" time without time zone NOT NULL,
    "estado" "Citas_estado_enum" DEFAULT 'Pendiente' NOT NULL,
    "notas" text,
    "motivo" text,
    "duracion_minutos" integer DEFAULT '30' NOT NULL,
    "tipo" "Cita_tipo_enum" DEFAULT 'Normal' NOT NULL,
    "prioridad" "Cita_prioridad_enum" DEFAULT 'Media' NOT NULL,
    "inicio_ts" timestamp GENERATED ALWAYS AS ((fecha + hora)) STORED,
    "fin_ts" timestamp GENERATED ALWAYS AS (((fecha + hora) + ((duracion_minutos)::double precision * '00:01:00'))) STORED,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deleted" boolean DEFAULT false NOT NULL,
    "deleted_at" timestamptz,
    CONSTRAINT "Citas_pkey" PRIMARY KEY ("id_cita"),
    CONSTRAINT "citas_deleted_chk" CHECK ((((deleted = false) AND (deleted_at IS NULL)) OR ((deleted = true) AND (deleted_at IS NOT NULL)))),
    CONSTRAINT "citas_duracion_chk" CHECK ((duracion_minutos > 0))
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_citas_tenant ON public."Citas" USING btree (id_empresa, id_cita);

CREATE INDEX citas_no_solape_excl ON public."Citas" USING gist (id_empresa, id_empleado, tsrange(inicio_ts, fin_ts, '[)'::text)) WHERE (deleted = false);

CREATE INDEX idx_citas_id_empresa ON public."Citas" USING btree (id_empresa);

CREATE INDEX idx_citas_id_paciente ON public."Citas" USING btree (id_paciente);

CREATE INDEX idx_citas_id_empleado ON public."Citas" USING btree (id_empleado);

CREATE INDEX idx_citas_fecha ON public."Citas" USING btree (fecha);

CREATE INDEX idx_citas_deleted ON public."Citas" USING btree (deleted);


DELIMITER ;;

CREATE TRIGGER "tr_citas_set_updated_at" BEFORE UPDATE ON "public"."Citas" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Citas_Productos_Usados";
CREATE TABLE "public"."Citas_Productos_Usados" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_cita" integer NOT NULL,
    "id_producto" integer NOT NULL,
    "id_lote" integer NOT NULL,
    "cantidad" integer NOT NULL,
    "fecha" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "Citas_Productos_Usados_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "citas_prod_usados_cantidad_chk" CHECK ((cantidad > 0))
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_citas_prod_usados ON public."Citas_Productos_Usados" USING btree (id_empresa, id_cita, id_producto, id_lote);


DELIMITER ;;

CREATE TRIGGER "tr_citas_prod_usados_set_updated_at" BEFORE UPDATE ON "public"."Citas_Productos_Usados" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Citas_Tratamientos";
CREATE TABLE "public"."Citas_Tratamientos" (
    "id_cita_tratamiento" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_cita" integer NOT NULL,
    "id_tratamiento" integer NOT NULL,
    "unidades" integer DEFAULT '1' NOT NULL,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "Citas_Tratamientos_pkey" PRIMARY KEY ("id_cita_tratamiento"),
    CONSTRAINT "citas_trat_unidades_chk" CHECK ((unidades > 0))
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_citas_trat_tenant ON public."Citas_Tratamientos" USING btree (id_empresa, id_cita, id_tratamiento);


DELIMITER ;;

CREATE TRIGGER "tr_citas_trat_set_updated_at" BEFORE UPDATE ON "public"."Citas_Tratamientos" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Clinicas";
CREATE TABLE "public"."Clinicas" (
    "id_clinica" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "nombre" character varying(150) NOT NULL,
    "telefono" character varying(20),
    "email_recordatorios" character varying(150),
    "telefono_recordatorios" character varying(20),
    "nombre_remitente" character varying(150),
    "direccion" character varying(255),
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deleted" boolean DEFAULT false NOT NULL,
    "deleted_at" timestamptz,
    CONSTRAINT "Clinicas_pkey" PRIMARY KEY ("id_clinica"),
    CONSTRAINT "clinicas_deleted_chk" CHECK ((((deleted = false) AND (deleted_at IS NULL)) OR ((deleted = true) AND (deleted_at IS NOT NULL)))),
    CONSTRAINT "clinicas_nombre_chk" CHECK ((length(TRIM(BOTH FROM nombre)) > 0))
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_clinicas_tenant ON public."Clinicas" USING btree (id_empresa, id_clinica);

CREATE INDEX idx_clinicas_id_empresa ON public."Clinicas" USING btree (id_empresa);


DELIMITER ;;

CREATE TRIGGER "tr_clinicas_set_updated_at" BEFORE UPDATE ON "public"."Clinicas" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Consentimientos";
CREATE TABLE "public"."Consentimientos" (
    "id_consentimiento" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_paciente" integer NOT NULL,
    "tipo" character varying(100) NOT NULL,
    "estado" "Consentimiento_estado_enum" DEFAULT 'Pendiente' NOT NULL,
    "fecha" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "Consentimientos_pkey" PRIMARY KEY ("id_consentimiento"),
    CONSTRAINT "consentimientos_tipo_chk" CHECK ((length(TRIM(BOTH FROM tipo)) > 0))
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_consentimientos_tenant ON public."Consentimientos" USING btree (id_empresa, id_consentimiento);


DELIMITER ;;

CREATE TRIGGER "tr_consentimientos_set_updated_at" BEFORE UPDATE ON "public"."Consentimientos" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Disponibilidad";
CREATE TABLE "public"."Disponibilidad" (
    "id_disponibilidad" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_clinica" integer,
    "id_empleado" integer NOT NULL,
    "dia_semana" "Dia_semana_enum" NOT NULL,
    "hora_inicio" time without time zone NOT NULL,
    "hora_fin" time without time zone NOT NULL,
    "duracion_slot" integer DEFAULT '30' NOT NULL,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "Disponibilidad_pkey" PRIMARY KEY ("id_disponibilidad"),
    CONSTRAINT "disponibilidad_horas_chk" CHECK ((hora_inicio < hora_fin)),
    CONSTRAINT "disponibilidad_slot_chk" CHECK ((duracion_slot > 0))
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_disponibilidad_tenant ON public."Disponibilidad" USING btree (id_empresa, id_disponibilidad);


DELIMITER ;;

CREATE TRIGGER "tr_disponibilidad_set_updated_at" BEFORE UPDATE ON "public"."Disponibilidad" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Documentos";
CREATE TABLE "public"."Documentos" (
    "id_documento" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_historial" integer NOT NULL,
    "nombre_archivo" character varying(255),
    "url_archivo" text,
    "tipo_documento" character varying(50),
    "fecha_subida" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deleted" boolean DEFAULT false NOT NULL,
    "deleted_at" timestamptz,
    CONSTRAINT "Documentos_pkey" PRIMARY KEY ("id_documento"),
    CONSTRAINT "documentos_deleted_chk" CHECK ((((deleted = false) AND (deleted_at IS NULL)) OR ((deleted = true) AND (deleted_at IS NOT NULL))))
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_documentos_tenant ON public."Documentos" USING btree (id_empresa, id_documento);


DELIMITER ;;

CREATE TRIGGER "tr_documentos_set_updated_at" BEFORE UPDATE ON "public"."Documentos" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Empleados";
CREATE TABLE "public"."Empleados" (
    "id_empleado" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_clinica" integer,
    "id_usuario" integer NOT NULL,
    "especialidad" character varying(100),
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "Empleados_pkey" PRIMARY KEY ("id_empleado")
)
WITH (oids = false);

CREATE UNIQUE INDEX "Empleados_id_usuario_key" ON public."Empleados" USING btree (id_usuario);

CREATE UNIQUE INDEX ux_empleados_tenant ON public."Empleados" USING btree (id_empresa, id_empleado);


DELIMITER ;;

CREATE TRIGGER "tr_empleados_set_updated_at" BEFORE UPDATE ON "public"."Empleados" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Empresas";
CREATE TABLE "public"."Empresas" (
    "id_empresa" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nombre" character varying(150) NOT NULL,
    "nif" character varying(50),
    "email" character varying(150),
    "telefono" character varying(20),
    "email_recordatorios" character varying(150),
    "telefono_recordatorios" character varying(20),
    "nombre_remitente" character varying(150),
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deleted" boolean DEFAULT false NOT NULL,
    "deleted_at" timestamptz,
    CONSTRAINT "Empresas_pkey" PRIMARY KEY ("id_empresa"),
    CONSTRAINT "empresas_deleted_chk" CHECK ((((deleted = false) AND (deleted_at IS NULL)) OR ((deleted = true) AND (deleted_at IS NOT NULL)))),
    CONSTRAINT "empresas_nombre_chk" CHECK ((length(TRIM(BOTH FROM nombre)) > 0))
)
WITH (oids = false);


DELIMITER ;;

CREATE TRIGGER "tr_empresas_set_updated_at" BEFORE UPDATE ON "public"."Empresas" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Factura_Tratamientos";
CREATE TABLE "public"."Factura_Tratamientos" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_factura" integer NOT NULL,
    "id_tratamiento" integer NOT NULL,
    "unidades" integer DEFAULT '1' NOT NULL,
    "precio_unitario" numeric(10,2),
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "Factura_Tratamientos_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "factura_trat_unidades_chk" CHECK ((unidades > 0)),
    CONSTRAINT "factura_trat_precio_chk" CHECK (((precio_unitario IS NULL) OR (precio_unitario >= (0)::numeric)))
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_factura_trat_tenant ON public."Factura_Tratamientos" USING btree (id_empresa, id_factura, id_tratamiento);


DELIMITER ;;

CREATE TRIGGER "tr_factura_trat_set_updated_at" BEFORE UPDATE ON "public"."Factura_Tratamientos" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Facturacion";
CREATE TABLE "public"."Facturacion" (
    "id_factura" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_clinica" integer,
    "id_paciente" integer NOT NULL,
    "id_cita" integer,
    "id_presupuesto" integer,
    "fecha_emision" date NOT NULL,
    "importe_total" numeric(10,2) NOT NULL,
    "descuento" numeric(10,2) DEFAULT '0' NOT NULL,
    "pago_status" "Facturacion_pago_status_enum" DEFAULT 'Pendiente' NOT NULL,
    "tipo_pago" "Tipo_pago_enum" NOT NULL,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "Facturacion_pkey" PRIMARY KEY ("id_factura"),
    CONSTRAINT "facturacion_importe_chk" CHECK ((importe_total >= (0)::numeric)),
    CONSTRAINT "facturacion_descuento_chk" CHECK (((descuento >= (0)::numeric) AND (descuento <= importe_total)))
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_facturacion_tenant ON public."Facturacion" USING btree (id_empresa, id_factura);

CREATE INDEX idx_facturacion_id_empresa ON public."Facturacion" USING btree (id_empresa);

CREATE INDEX idx_facturacion_id_paciente ON public."Facturacion" USING btree (id_paciente);

CREATE INDEX idx_facturacion_fecha_emision ON public."Facturacion" USING btree (fecha_emision DESC);

CREATE INDEX idx_facturacion_pago_status ON public."Facturacion" USING btree (pago_status);


DELIMITER ;;

CREATE TRIGGER "tr_facturacion_set_updated_at" BEFORE UPDATE ON "public"."Facturacion" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Historial";
CREATE TABLE "public"."Historial" (
    "id_historial" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_paciente" integer NOT NULL,
    "id_empleado" integer NOT NULL,
    "fecha" date NOT NULL,
    "descripcion" text,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deleted" boolean DEFAULT false NOT NULL,
    "deleted_at" timestamptz,
    CONSTRAINT "Historial_pkey" PRIMARY KEY ("id_historial"),
    CONSTRAINT "historial_deleted_chk" CHECK ((((deleted = false) AND (deleted_at IS NULL)) OR ((deleted = true) AND (deleted_at IS NOT NULL))))
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_historial_tenant ON public."Historial" USING btree (id_empresa, id_historial);


DELIMITER ;;

CREATE TRIGGER "tr_historial_set_updated_at" BEFORE UPDATE ON "public"."Historial" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "MovimientosStock";
CREATE TABLE "public"."MovimientosStock" (
    "id_movimiento" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_clinica" integer,
    "id_producto" integer NOT NULL,
    "id_lote" integer,
    "tipo" "Movimiento_stock_tipo_enum" NOT NULL,
    "cantidad" integer NOT NULL,
    "fecha" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "motivo" text,
    "id_usuario" integer,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "MovimientosStock_pkey" PRIMARY KEY ("id_movimiento"),
    CONSTRAINT "movimientos_stock_cantidad_chk" CHECK ((cantidad > 0))
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_movimientos_stock_tenant ON public."MovimientosStock" USING btree (id_empresa, id_movimiento);


DELIMITER ;;

CREATE TRIGGER "tr_movimientos_stock_set_updated_at" BEFORE UPDATE ON "public"."MovimientosStock" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Notificaciones";
CREATE TABLE "public"."Notificaciones" (
    "id_notificacion" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_usuario" integer NOT NULL,
    "id_paciente" integer,
    "titulo" character varying(255) NOT NULL,
    "mensaje" text NOT NULL,
    "leida" boolean DEFAULT false NOT NULL,
    "fecha_envio" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "Notificaciones_pkey" PRIMARY KEY ("id_notificacion"),
    CONSTRAINT "notificaciones_titulo_chk" CHECK ((length(TRIM(BOTH FROM titulo)) > 0))
)
WITH (oids = false);

CREATE INDEX idx_notificaciones_id_usuario ON public."Notificaciones" USING btree (id_usuario);

CREATE INDEX idx_notificaciones_id_empresa ON public."Notificaciones" USING btree (id_empresa);

CREATE INDEX idx_notificaciones_leida ON public."Notificaciones" USING btree (leida);


DELIMITER ;;

CREATE TRIGGER "tr_notificaciones_set_updated_at" BEFORE UPDATE ON "public"."Notificaciones" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Pacientes";
CREATE TABLE "public"."Pacientes" (
    "id_paciente" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_clinica" integer,
    "id_usuario" integer,
    "nombre" character varying(100),
    "apellido" character varying(100),
    "email" character varying(150),
    "fecha_nacimiento" date,
    "telefono" character varying(20),
    "direccion" character varying(255),
    "historial_medico" text,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deleted" boolean DEFAULT false NOT NULL,
    "deleted_at" timestamptz,
    CONSTRAINT "Pacientes_pkey" PRIMARY KEY ("id_paciente"),
    CONSTRAINT "pacientes_deleted_chk" CHECK ((((deleted = false) AND (deleted_at IS NULL)) OR ((deleted = true) AND (deleted_at IS NOT NULL))))
)
WITH (oids = false);

CREATE UNIQUE INDEX "Pacientes_id_usuario_key" ON public."Pacientes" USING btree (id_usuario);

CREATE UNIQUE INDEX ux_pacientes_tenant ON public."Pacientes" USING btree (id_empresa, id_paciente);

CREATE INDEX idx_pacientes_id_empresa ON public."Pacientes" USING btree (id_empresa);

CREATE INDEX idx_pacientes_id_clinica ON public."Pacientes" USING btree (id_clinica);

CREATE INDEX idx_pacientes_nombre ON public."Pacientes" USING btree (nombre);

CREATE INDEX idx_pacientes_apellido ON public."Pacientes" USING btree (apellido);

CREATE INDEX idx_pacientes_email ON public."Pacientes" USING btree (email);

CREATE INDEX idx_pacientes_telefono ON public."Pacientes" USING btree (telefono);

CREATE INDEX idx_pacientes_fecha_creacion ON public."Pacientes" USING btree (fecha_creacion DESC);

CREATE INDEX idx_pacientes_deleted ON public."Pacientes" USING btree (deleted);


DELIMITER ;;

CREATE TRIGGER "tr_pacientes_set_updated_at" BEFORE UPDATE ON "public"."Pacientes" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "PagosFactura";
CREATE TABLE "public"."PagosFactura" (
    "id_pago" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_factura" integer NOT NULL,
    "monto" numeric(10,2) NOT NULL,
    "fecha" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "tipo_pago" "Tipo_pago_enum" NOT NULL,
    "id_usuario" integer,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "PagosFactura_pkey" PRIMARY KEY ("id_pago"),
    CONSTRAINT "pagos_factura_monto_chk" CHECK ((monto > (0)::numeric))
)
WITH (oids = false);


DELIMITER ;;

CREATE TRIGGER "tr_pagos_factura_set_updated_at" BEFORE UPDATE ON "public"."PagosFactura" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "PedidoProducto";
CREATE TABLE "public"."PedidoProducto" (
    "id_detalle" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_pedido" integer NOT NULL,
    "id_producto" integer NOT NULL,
    "cantidad" integer NOT NULL,
    "precio_unitario" numeric(10,2),
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "PedidoProducto_pkey" PRIMARY KEY ("id_detalle"),
    CONSTRAINT "pedido_producto_cantidad_chk" CHECK ((cantidad > 0)),
    CONSTRAINT "pedido_producto_precio_chk" CHECK (((precio_unitario IS NULL) OR (precio_unitario >= (0)::numeric)))
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_pedido_producto_tenant ON public."PedidoProducto" USING btree (id_empresa, id_pedido, id_producto);


DELIMITER ;;

CREATE TRIGGER "tr_pedido_producto_set_updated_at" BEFORE UPDATE ON "public"."PedidoProducto" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "PedidosProveedores";
CREATE TABLE "public"."PedidosProveedores" (
    "id_pedido" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_proveedor" integer NOT NULL,
    "fecha_pedido" date NOT NULL,
    "fecha_entrega" date,
    "estado" "Estado_pedido_enum" DEFAULT 'Pendiente' NOT NULL,
    "total" numeric(10,2),
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "PedidosProveedores_pkey" PRIMARY KEY ("id_pedido"),
    CONSTRAINT "pedidos_total_chk" CHECK (((total IS NULL) OR (total >= (0)::numeric))),
    CONSTRAINT "pedidos_fechas_chk" CHECK (((fecha_entrega IS NULL) OR (fecha_entrega >= fecha_pedido)))
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_pedidos_tenant ON public."PedidosProveedores" USING btree (id_empresa, id_pedido);


DELIMITER ;;

CREATE TRIGGER "tr_pedidos_set_updated_at" BEFORE UPDATE ON "public"."PedidosProveedores" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Presupuesto_Tratamientos";
CREATE TABLE "public"."Presupuesto_Tratamientos" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_presupuesto" integer NOT NULL,
    "id_tratamiento" integer NOT NULL,
    "unidades" integer DEFAULT '1' NOT NULL,
    "precio_unitario" numeric(10,2),
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "Presupuesto_Tratamientos_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "pres_trat_unidades_chk" CHECK ((unidades > 0)),
    CONSTRAINT "pres_trat_precio_chk" CHECK (((precio_unitario IS NULL) OR (precio_unitario >= (0)::numeric)))
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_presupuesto_trat_tenant ON public."Presupuesto_Tratamientos" USING btree (id_empresa, id_presupuesto, id_tratamiento);


DELIMITER ;;

CREATE TRIGGER "tr_pres_trat_set_updated_at" BEFORE UPDATE ON "public"."Presupuesto_Tratamientos" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Presupuestos";
CREATE TABLE "public"."Presupuestos" (
    "id_presupuesto" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_clinica" integer,
    "id_paciente" integer NOT NULL,
    "id_tratamiento" integer,
    "fecha_emision" date NOT NULL,
    "importe_total" numeric(10,2) NOT NULL,
    "descuento" numeric(10,2) DEFAULT '0' NOT NULL,
    "estado" "Facturacion_pago_status_enum" DEFAULT 'Pendiente' NOT NULL,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "Presupuestos_pkey" PRIMARY KEY ("id_presupuesto"),
    CONSTRAINT "presupuestos_importe_chk" CHECK ((importe_total >= (0)::numeric)),
    CONSTRAINT "presupuestos_descuento_chk" CHECK (((descuento >= (0)::numeric) AND (descuento <= importe_total)))
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_presupuestos_tenant ON public."Presupuestos" USING btree (id_empresa, id_presupuesto);


DELIMITER ;;

CREATE TRIGGER "tr_presupuestos_set_updated_at" BEFORE UPDATE ON "public"."Presupuestos" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Productos";
CREATE TABLE "public"."Productos" (
    "id_producto" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "nombre_producto" character varying(150) NOT NULL,
    "precio" numeric(10,2),
    "coste" numeric(10,2),
    "vendible" boolean DEFAULT true NOT NULL,
    "stock_actual" integer DEFAULT '0' NOT NULL,
    "stock_minimo" integer DEFAULT '0' NOT NULL,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "Productos_pkey" PRIMARY KEY ("id_producto"),
    CONSTRAINT "productos_nombre_chk" CHECK ((length(TRIM(BOTH FROM nombre_producto)) > 0)),
    CONSTRAINT "productos_precio_chk" CHECK (((precio IS NULL) OR (precio >= (0)::numeric))),
    CONSTRAINT "productos_coste_chk" CHECK (((coste IS NULL) OR (coste >= (0)::numeric))),
    CONSTRAINT "productos_stock_actual_chk" CHECK ((stock_actual >= 0)),
    CONSTRAINT "productos_stock_minimo_chk" CHECK ((stock_minimo >= 0))
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_productos_tenant ON public."Productos" USING btree (id_empresa, id_producto);


DELIMITER ;;

CREATE TRIGGER "tr_productos_set_updated_at" BEFORE UPDATE ON "public"."Productos" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Productos_Lotes";
CREATE TABLE "public"."Productos_Lotes" (
    "id_lote" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_producto" integer NOT NULL,
    "numero_lote" character varying(100) NOT NULL,
    "fecha_caducidad" date,
    "stock_lote" integer NOT NULL,
    "coste_unitario" numeric(10,2),
    "fecha_entrada" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deleted" boolean DEFAULT false NOT NULL,
    "deleted_at" timestamptz,
    CONSTRAINT "Productos_Lotes_pkey" PRIMARY KEY ("id_lote"),
    CONSTRAINT "productos_lotes_deleted_chk" CHECK ((((deleted = false) AND (deleted_at IS NULL)) OR ((deleted = true) AND (deleted_at IS NOT NULL)))),
    CONSTRAINT "productos_lotes_numero_chk" CHECK ((length(TRIM(BOTH FROM numero_lote)) > 0)),
    CONSTRAINT "productos_lotes_stock_chk" CHECK ((stock_lote >= 0)),
    CONSTRAINT "productos_lotes_coste_chk" CHECK (((coste_unitario IS NULL) OR (coste_unitario >= (0)::numeric)))
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_productos_lotes_tenant ON public."Productos_Lotes" USING btree (id_empresa, id_lote);


DELIMITER ;;

CREATE TRIGGER "tr_productos_lotes_set_updated_at" BEFORE UPDATE ON "public"."Productos_Lotes" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Productos_Tratamientos";
CREATE TABLE "public"."Productos_Tratamientos" (
    "id_producto_tratamiento" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_producto" integer NOT NULL,
    "id_tratamiento" integer NOT NULL,
    "unidades" integer,
    "consumible" boolean DEFAULT true NOT NULL,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "Productos_Tratamientos_pkey" PRIMARY KEY ("id_producto_tratamiento"),
    CONSTRAINT "productos_tratamientos_unidades_chk" CHECK (((unidades IS NULL) OR (unidades > 0)))
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_productos_tratamientos_tenant ON public."Productos_Tratamientos" USING btree (id_empresa, id_producto, id_tratamiento);


DELIMITER ;;

CREATE TRIGGER "tr_productos_tratamientos_set_updated_at" BEFORE UPDATE ON "public"."Productos_Tratamientos" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Proveedores";
CREATE TABLE "public"."Proveedores" (
    "id_proveedor" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "nombre" character varying(150) NOT NULL,
    "contacto" character varying(100),
    "email" character varying(150),
    "telefono" character varying(20),
    "direccion" character varying(255),
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "Proveedores_pkey" PRIMARY KEY ("id_proveedor"),
    CONSTRAINT "proveedores_nombre_chk" CHECK ((length(TRIM(BOTH FROM nombre)) > 0))
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_proveedores_tenant ON public."Proveedores" USING btree (id_empresa, id_proveedor);


DELIMITER ;;

CREATE TRIGGER "tr_proveedores_set_updated_at" BEFORE UPDATE ON "public"."Proveedores" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Recordatorios";
CREATE TABLE "public"."Recordatorios" (
    "id_recordatorio" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_paciente" integer NOT NULL,
    "id_cita" integer,
    "tipo_mensaje" "Tipo_mensaje_enum" NOT NULL,
    "estado" "Recordatorio_estado_enum" DEFAULT 'Pendiente' NOT NULL,
    "fecha_envio_programada" timestamptz NOT NULL,
    "fecha_envio_real" timestamptz,
    "mensaje" text,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "Recordatorios_pkey" PRIMARY KEY ("id_recordatorio"),
    CONSTRAINT "recordatorios_mensaje_chk" CHECK ((length(TRIM(BOTH FROM mensaje)) > 0))
)
WITH (oids = false);


DELIMITER ;;

CREATE TRIGGER "tr_recordatorios_set_updated_at" BEFORE UPDATE ON "public"."Recordatorios" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Tratamientos";
CREATE TABLE "public"."Tratamientos" (
    "id_tratamiento" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "nombre_tratamiento" character varying(150) NOT NULL,
    "descripcion" text,
    "unidades" numeric(10,2),
    "precio" numeric(10,2),
    "duracion_minima" integer,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "Tratamientos_pkey" PRIMARY KEY ("id_tratamiento"),
    CONSTRAINT "tratamientos_nombre_chk" CHECK ((length(TRIM(BOTH FROM nombre_tratamiento)) > 0)),
    CONSTRAINT "tratamientos_unidades_chk" CHECK (((unidades IS NULL) OR (unidades >= (0)::numeric))),
    CONSTRAINT "tratamientos_precio_chk" CHECK (((precio IS NULL) OR (precio >= (0)::numeric))),
    CONSTRAINT "tratamientos_duracion_chk" CHECK (((duracion_minima IS NULL) OR (duracion_minima > 0)))
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_tratamientos_tenant ON public."Tratamientos" USING btree (id_empresa, id_tratamiento);


DELIMITER ;;

CREATE TRIGGER "tr_tratamientos_set_updated_at" BEFORE UPDATE ON "public"."Tratamientos" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Usuarios";
CREATE TABLE "public"."Usuarios" (
    "id_usuario" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nombre" character varying(100) NOT NULL,
    "apellido" character varying(100) NOT NULL,
    "email" character varying(150) NOT NULL,
    "password" character varying(255) NOT NULL,
    "estado" "Estado_usuario_enum" DEFAULT 'activo' NOT NULL,
    "is_superadmin" boolean DEFAULT false NOT NULL,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "deleted" boolean DEFAULT false NOT NULL,
    "deleted_at" timestamptz,
    CONSTRAINT "Usuarios_pkey" PRIMARY KEY ("id_usuario"),
    CONSTRAINT "usuarios_deleted_chk" CHECK ((((deleted = false) AND (deleted_at IS NULL)) OR ((deleted = true) AND (deleted_at IS NOT NULL)))),
    CONSTRAINT "usuarios_email_chk" CHECK ((length(TRIM(BOTH FROM email)) > 3))
)
WITH (oids = false);

CREATE INDEX idx_usuarios_email ON public."Usuarios" USING btree (email);

CREATE INDEX idx_usuarios_deleted ON public."Usuarios" USING btree (deleted);


DELIMITER ;;

CREATE TRIGGER "tr_usuarios_set_updated_at" BEFORE UPDATE ON "public"."Usuarios" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Usuarios_Clinicas";
CREATE TABLE "public"."Usuarios_Clinicas" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_empresa" integer NOT NULL,
    "id_usuario" integer NOT NULL,
    "id_clinica" integer NOT NULL,
    "menu_citas" boolean DEFAULT true NOT NULL,
    "menu_pacientes" boolean DEFAULT true NOT NULL,
    "menu_facturacion" boolean DEFAULT true NOT NULL,
    "menu_productos" boolean DEFAULT true NOT NULL,
    "menu_proveedores" boolean DEFAULT true NOT NULL,
    "menu_tratamientos" boolean DEFAULT true NOT NULL,
    "menu_usuarios" boolean DEFAULT true NOT NULL,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "Usuarios_Clinicas_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_usuarios_clinicas_usuario_clinica ON public."Usuarios_Clinicas" USING btree (id_usuario, id_clinica);

CREATE INDEX idx_usuarios_clinicas_id_empresa ON public."Usuarios_Clinicas" USING btree (id_empresa);

CREATE INDEX idx_usuarios_clinicas_id_usuario ON public."Usuarios_Clinicas" USING btree (id_usuario);

CREATE INDEX idx_usuarios_clinicas_id_clinica ON public."Usuarios_Clinicas" USING btree (id_clinica);


DELIMITER ;;

CREATE TRIGGER "tr_usuarios_clinicas_set_updated_at" BEFORE UPDATE ON "public"."Usuarios_Clinicas" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "Usuarios_Empresas";
CREATE TABLE "public"."Usuarios_Empresas" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_usuario" integer NOT NULL,
    "id_empresa" integer NOT NULL,
    "fecha_creacion" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "Usuarios_Empresas_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

CREATE UNIQUE INDEX ux_usuarios_empresas_usuario_empresa ON public."Usuarios_Empresas" USING btree (id_usuario, id_empresa);

CREATE INDEX idx_usuarios_empresas_id_usuario ON public."Usuarios_Empresas" USING btree (id_usuario);

CREATE INDEX idx_usuarios_empresas_id_empresa ON public."Usuarios_Empresas" USING btree (id_empresa);


DELIMITER ;;

CREATE TRIGGER "tr_usuarios_empresas_set_updated_at" BEFORE UPDATE ON "public"."Usuarios_Empresas" FOR EACH ROW EXECUTE FUNCTION set_updated_at();;

DELIMITER ;

DROP TABLE IF EXISTS "cache";
CREATE TABLE "public"."cache" (
    "key" character varying(255) NOT NULL,
    "value" text NOT NULL,
    "expiration" integer NOT NULL,
    CONSTRAINT "cache_pkey" PRIMARY KEY ("key")
)
WITH (oids = false);


DROP TABLE IF EXISTS "cache_locks";
CREATE TABLE "public"."cache_locks" (
    "key" character varying(255) NOT NULL,
    "owner" character varying(255) NOT NULL,
    "expiration" integer NOT NULL,
    CONSTRAINT "cache_locks_pkey" PRIMARY KEY ("key")
)
WITH (oids = false);


DROP TABLE IF EXISTS "failed_jobs";
CREATE TABLE "public"."failed_jobs" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "uuid" character varying(255) NOT NULL,
    "connection" text NOT NULL,
    "queue" text NOT NULL,
    "payload" text NOT NULL,
    "exception" text NOT NULL,
    "failed_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "failed_jobs_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

CREATE UNIQUE INDEX failed_jobs_uuid_key ON public.failed_jobs USING btree (uuid);


DROP TABLE IF EXISTS "jobs";
CREATE TABLE "public"."jobs" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "queue" character varying(255) NOT NULL,
    "payload" text NOT NULL,
    "attempts" smallint NOT NULL,
    "reserved_at" integer,
    "available_at" integer NOT NULL,
    "created_at" integer NOT NULL,
    CONSTRAINT "jobs_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

CREATE INDEX jobs_queue_index ON public.jobs USING btree (queue);


DROP TABLE IF EXISTS "sessions";
CREATE TABLE "public"."sessions" (
    "id" character varying(255) NOT NULL,
    "user_id" bigint,
    "ip_address" character varying(45),
    "user_agent" text,
    "payload" text NOT NULL,
    "last_activity" integer NOT NULL,
    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

CREATE INDEX sessions_user_id_index ON public.sessions USING btree (user_id);

CREATE INDEX sessions_last_activity_index ON public.sessions USING btree (last_activity);


-- 2026-02-09 06:07:28 UTC
